In [17]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [18]:
import sys 

sys.path.append("../")

In [19]:
import pandas as pd
from src.data_cleaning import *
from src.data_investigation import featureType,cardinality
from src.configuration import RAW_DATA,EXPORT_PATH
from src.helperFunc import saveFile

df=pd.read_csv(RAW_DATA)
df=df.copy()

df=uncapitalize(df)
df.head(2)

   unnamed: 0  age gender  bmi  chol   tg  hdl  ldl    cr  bun  diagnosis
0           0   50      F   24   4.2  0.9  2.4  1.4  46.0  4.7          0
1           1   26      M   23   3.7  1.4  1.1  2.1  62.0  4.5          0

In [20]:
df=drop_duplicates(df)
df.head(3)

   unnamed: 0  age gender  bmi  chol   tg  hdl  ldl    cr  bun  diagnosis
0           0   50      F   24   4.2  0.9  2.4  1.4  46.0  4.7          0
1           1   26      M   23   3.7  1.4  1.1  2.1  62.0  4.5          0
2           2   33      M   21   4.9  1.0  0.8  2.0  46.0  7.1          0

In [21]:
df=drop_col(df,'unnamed: 0')
df.head(2)

   age gender  bmi  chol   tg  hdl  ldl    cr  bun  diagnosis
0   50      F   24   4.2  0.9  2.4  1.4  46.0  4.7          0
1   26      M   23   3.7  1.4  1.1  2.1  62.0  4.5          0

Dropped the unnecessary unnamed columns!

In [22]:
df=gender_fix(df,'gender')
_,cat=featureType(df)
cardinality(cat,df)

['F' 'M']
gender
M    3256
F    1876
Name: count, dtype: int64

Categorical value 'f' replaced with 'F'!

In [23]:

cols = ['hdl', 'tg', 'chol']

df[cols] = df[cols].replace(0.0, np.nan)

df[cols] = df[cols].fillna(df[cols].median())

Imputing rows where values are 0 !

In [24]:

df = df[df['cr'] != 800]

Dropped some rows where 'cr' had anomalies !

In [25]:
df['gender']=df['gender'].map({'M':1,"F":0})

Mapping Male to 1 and Female to 0!

In [26]:
df.tail()

      age  gender  bmi  chol    tg   hdl   ldl    cr   bun  diagnosis
5127   54       1   23  5.00  1.50  1.24  2.98  77.0  3.50          1
5128   50       0   22  4.37  2.09  1.37  2.29  47.3  4.40          1
5129   67       1   24  3.89  1.38  1.14  2.17  70.6  4.73          1
5130   60       0   29  5.91  1.29  1.73  2.85  50.2  7.33          1
5131   37       1   34  5.42  2.66  1.08  2.87  75.5  4.61          1

In [27]:
df=df.sample(frac=1, random_state=42).reset_index(drop=True)

Shuffling the dataset because the diagnosis are separated !

In [28]:
df.tail()

      age  gender  bmi  chol    tg   hdl   ldl    cr   bun  diagnosis
5124   65       1   26  4.20  2.20  1.75  2.05  67.0  3.46          1
5125   55       0   34  6.10  1.60  1.40  4.00  63.0  4.90          1
5126   39       1   22  5.36  3.45  1.37  2.64  67.9  4.60          0
5127   39       1   22  4.76  1.14  1.16  2.81  88.6  4.48          0
5128   27       0   23  5.37  1.46  1.56  3.18  56.6  3.32          0

In [ ]:
saveFile(df,EXPORT_PATH)