In [18]:
import os
os.chdir(r'C:\Users\Lenovo\Desktop\Diabetes_Classifier\notebooks')
os.chdir("..")
print(os.getcwd())

C:\Users\Lenovo\Desktop\Diabetes_Classifier

In [19]:
import pandas as pd
from src.data_cleaning import *
from src.data_investigation import featureType,cardinality
from src.helperFunc import saveFile

PATH='data/clean/Diabetes Classifier Clean.csv'
df=pd.read_csv("data/raw/Diabetes Classification.csv")
df=df.copy()

df=uncapitalize(df)
df.head(2)

   unnamed: 0  age gender  bmi  chol   tg  hdl  ldl    cr  bun  diagnosis
0           0   50      F   24   4.2  0.9  2.4  1.4  46.0  4.7          0
1           1   26      M   23   3.7  1.4  1.1  2.1  62.0  4.5          0

In [20]:
df=drop_duplicates(df)
df.head(3)

   unnamed: 0  age gender  bmi  chol   tg  hdl  ldl    cr  bun  diagnosis
0           0   50      F   24   4.2  0.9  2.4  1.4  46.0  4.7          0
1           1   26      M   23   3.7  1.4  1.1  2.1  62.0  4.5          0
2           2   33      M   21   4.9  1.0  0.8  2.0  46.0  7.1          0

In [21]:
df=drop_col(df,'unnamed: 0')
df.head(2)

   age gender  bmi  chol   tg  hdl  ldl    cr  bun  diagnosis
0   50      F   24   4.2  0.9  2.4  1.4  46.0  4.7          0
1   26      M   23   3.7  1.4  1.1  2.1  62.0  4.5          0

Dropped the unnecessary unnamed columns!

In [22]:
df=gender_fix(df,'gender')
_,cat=featureType(df)
cardinality(cat,df)

<StringArray>
['F', 'M']
Length: 2, dtype: str
gender
M    3256
F    1876
Name: count, dtype: int64

In [23]:

cols = ['hdl', 'tg', 'chol']

df[cols] = df[cols].replace(0.0, np.nan)

df[cols] = df[cols].fillna(df[cols].median())

Imputing rows where values are 0 !

Categorical value 'f' replaced with 'F'!

In [24]:
saveFile(df,PATH)