In [26]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [27]:
import os
os.chdir(r'C:\Users\Lenovo\Desktop\Diabetes_Classifier\notebooks')
os.chdir("..")
print(os.getcwd())

C:\Users\Lenovo\Desktop\Diabetes_Classifier

In [28]:
from modeling.XGBoost import XGBoost
from modeling.RandomForest import RandomForest
from modeling.KNN import KNN
from modeling.MLP import MLP
from sklearn.linear_model import LogisticRegression
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score,recall_score,precision_score,balanced_accuracy_score,roc_auc_score,accuracy_score

In [29]:
PATH="data/preprocessed/preprocessed.csv"
df=pd.read_csv(PATH)
df.head()
df.columns = df.columns.str.strip()

In [30]:


y=df['diagnosis']
X=df.drop(['diagnosis'],axis=1)
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [31]:

xgb=XGBoost()
xgb_params={'n_estimators': 7300, 'max_depth': 9,'learning_rate': 0.042826934350783406, 'gamma': 0.8864325835995647, 'min_child_weight': 1, 'reg_alpha': 0.00019361810915135758, 'reg_lambda': 3.6728295355053825e-06, 'subsample': 0.6459234341228212, 'colsample_bytree': 0.2968183856347904, 'tree_method': 'hist', 'n_jobs': -1}
xgb.set_params(xgb_params)
pd.set_option('display.max_rows',None)

#Optuna
params=xgb.hyperparameter_tuning(X,y,30)
xgb.set_params(params)

# Train and Test XGB
metrics=xgb.evaluation(X_train,y_train,5)
metrics.out()

[I 2026-07-29 18:05:14,949] A new study created in memory with name: no-name-1232b3cb-03af-43b7-8e38-8c259a03f636
[I 2026-07-29 18:06:47,755] Trial 0 finished with value: 0.8961993108981625 and parameters: {'n_estimators': 13600, 'max_depth': 15, 'learning_rate': 0.036146027758793366, 'gamma': 2.6974961369837263e-05, 'min_child_weight': 2, 'reg_alpha': 0.12719240403340698, 'reg_lambda': 0.28509554937772447, 'subsample': 0.22007941310457488, 'colsample_bytree': 0.5423752592919056}. Best is trial 0 with value: 0.8961993108981625.

{'n_estimators': 13600, 'max_depth': 15, 'learning_rate': 0.036146027758793366, 'gamma': 2.6974961369837263e-05, 'min_child_weight': 2, 'reg_alpha': 0.12719240403340698, 'reg_lambda': 0.28509554937772447, 'subsample': 0.22007941310457488, 'colsample_bytree': 0.5423752592919056, 'tree_method': 'hist', 'n_jobs': -1}
Accuracy: 0.8129385727653549
Precision: 0.7733469455998585
F1: 0.7530003519874484
Recall: 0.7340638027228876
Balanced Accuracy:0.7985366911297268
ROC-AUC: 0.8961993108981625

[I 2026-07-29 18:07:26,573] Trial 1 finished with value: 0.9043190892173397 and parameters: {'n_estimators': 7200, 'max_depth': 13, 'learning_rate': 0.0344477136670219, 'gamma': 2.9340337739707855e-06, 'min_child_weight': 7, 'reg_alpha': 9.185941329323505, 'reg_lambda': 0.02304226702848147, 'subsample': 0.9293643350641032, 'colsample_bytree': 0.9181164771526322}. Best is trial 1 with value: 0.9043190892173397.

{'n_estimators': 7200, 'max_depth': 13, 'learning_rate': 0.0344477136670219, 'gamma': 2.9340337739707855e-06, 'min_child_weight': 7, 'reg_alpha': 9.185941329323505, 'reg_lambda': 0.02304226702848147, 'subsample': 0.9293643350641032, 'colsample_bytree': 0.9181164771526322, 'tree_method': 'hist', 'n_jobs': -1}
Accuracy: 0.8168364490149965
Precision: 0.7784225738241701
F1: 0.758543233032546
Recall: 0.7400964723366205
Balanced Accuracy:0.8028261493937595
ROC-AUC: 0.9043190892173397

[I 2026-07-29 18:09:22,521] Trial 2 finished with value: 0.8982200471708172 and parameters: {'n_estimators': 14000, 'max_depth': 9, 'learning_rate': 0.012407708924952614, 'gamma': 1.8815485650020902e-05, 'min_child_weight': 10, 'reg_alpha': 0.0010497452795069676, 'reg_lambda': 0.4451624175681357, 'subsample': 0.946966996740366, 'colsample_bytree': 0.31599054929732545}. Best is trial 1 with value: 0.9043190892173397.

{'n_estimators': 14000, 'max_depth': 9, 'learning_rate': 0.012407708924952614, 'gamma': 1.8815485650020902e-05, 'min_child_weight': 10, 'reg_alpha': 0.0010497452795069676, 'reg_lambda': 0.4451624175681357, 'subsample': 0.946966996740366, 'colsample_bytree': 0.31599054929732545, 'tree_method': 'hist', 'n_jobs': -1}
Accuracy: 0.8144961288865353
Precision: 0.771793134236201
F1: 0.7565665754286484
Recall: 0.7420989660079848
Balanced Accuracy:0.8012801334575727
ROC-AUC: 0.8982200471708172

[I 2026-07-29 18:09:59,646] Trial 3 finished with value: 0.9070333078413493 and parameters: {'n_estimators': 10000, 'max_depth': 16, 'learning_rate': 0.04639150433495946, 'gamma': 0.7470866844040508, 'min_child_weight': 1, 'reg_alpha': 0.005791580864320127, 'reg_lambda': 5.269008299470182, 'subsample': 0.9452712798053784, 'colsample_bytree': 0.4739173215050985}. Best is trial 3 with value: 0.9070333078413493.

{'n_estimators': 10000, 'max_depth': 16, 'learning_rate': 0.04639150433495946, 'gamma': 0.7470866844040508, 'min_child_weight': 1, 'reg_alpha': 0.005791580864320127, 'reg_lambda': 5.269008299470182, 'subsample': 0.9452712798053784, 'colsample_bytree': 0.4739173215050985, 'tree_method': 'hist', 'n_jobs': -1}
Accuracy: 0.8119612565981653
Precision: 0.7699526035400359
F1: 0.7525315970498326
Recall: 0.7360700746841978
Balanced Accuracy:0.7981056902337373
ROC-AUC: 0.9070333078413493

[I 2026-07-29 18:11:30,597] Trial 4 finished with value: 0.8991520093681704 and parameters: {'n_estimators': 10500, 'max_depth': 18, 'learning_rate': 0.018688123979709828, 'gamma': 1.829838520391145e-05, 'min_child_weight': 4, 'reg_alpha': 0.00013276331652999554, 'reg_lambda': 0.0016032546665551912, 'subsample': 0.5699012737416504, 'colsample_bytree': 0.7011378956535876}. Best is trial 3 with value: 0.9070333078413493.

{'n_estimators': 10500, 'max_depth': 18, 'learning_rate': 0.018688123979709828, 'gamma': 1.829838520391145e-05, 'min_child_weight': 4, 'reg_alpha': 0.00013276331652999554, 'reg_lambda': 0.0016032546665551912, 'subsample': 0.5699012737416504, 'colsample_bytree': 0.7011378956535876, 'tree_method': 'hist', 'n_jobs': -1}
Accuracy: 0.8139117131788683
Precision: 0.7703903539277288
F1: 0.756098528052509
Recall: 0.742590143700961
Balanced Accuracy:0.8008885256645177
ROC-AUC: 0.8991520093681704

[I 2026-07-29 18:12:35,138] Trial 5 finished with value: 0.8995692689185792 and parameters: {'n_estimators': 7500, 'max_depth': 8, 'learning_rate': 0.017563260575251604, 'gamma': 7.310087494998486e-08, 'min_child_weight': 6, 'reg_alpha': 0.0023453642415770413, 'reg_lambda': 8.427968629995846e-07, 'subsample': 0.6768556788074839, 'colsample_bytree': 0.31560489919054957}. Best is trial 3 with value: 0.9070333078413493.

{'n_estimators': 7500, 'max_depth': 8, 'learning_rate': 0.017563260575251604, 'gamma': 7.310087494998486e-08, 'min_child_weight': 6, 'reg_alpha': 0.0023453642415770413, 'reg_lambda': 8.427968629995846e-07, 'subsample': 0.6768556788074839, 'colsample_bytree': 0.31560489919054957, 'tree_method': 'hist', 'n_jobs': -1}
Accuracy: 0.8131331249252636
Precision: 0.7709157841265493
F1: 0.7542832223462133
Recall: 0.7385763403483583
Balanced Accuracy:0.7995188206277596
ROC-AUC: 0.8995692689185792

[I 2026-07-29 18:13:39,013] Trial 6 finished with value: 0.8938710978369834 and parameters: {'n_estimators': 9400, 'max_depth': 12, 'learning_rate': 0.028468345582555662, 'gamma': 8.049710806392436e-07, 'min_child_weight': 7, 'reg_alpha': 0.00014816296325394093, 'reg_lambda': 1.964857393345104e-05, 'subsample': 0.23510247624508926, 'colsample_bytree': 0.9174948047874585}. Best is trial 3 with value: 0.9070333078413493.

{'n_estimators': 9400, 'max_depth': 12, 'learning_rate': 0.028468345582555662, 'gamma': 8.049710806392436e-07, 'min_child_weight': 7, 'reg_alpha': 0.00014816296325394093, 'reg_lambda': 1.964857393345104e-05, 'subsample': 0.23510247624508926, 'colsample_bytree': 0.9174948047874585, 'tree_method': 'hist', 'n_jobs': -1}
Accuracy: 0.8111858950633101
Precision: 0.7691188455827742
F1: 0.751350333900695
Recall: 0.7345625369957557
Balanced Accuracy:0.797195479328951
ROC-AUC: 0.8938710978369834

[I 2026-07-29 18:14:23,298] Trial 7 finished with value: 0.8947770381509444 and parameters: {'n_estimators': 6500, 'max_depth': 13, 'learning_rate': 0.1440597648337454, 'gamma': 3.228462198742689e-07, 'min_child_weight': 3, 'reg_alpha': 0.17872983601094317, 'reg_lambda': 7.824415298034274, 'subsample': 0.3608103460466552, 'colsample_bytree': 0.226757146849718}. Best is trial 3 with value: 0.9070333078413493.

{'n_estimators': 6500, 'max_depth': 13, 'learning_rate': 0.1440597648337454, 'gamma': 3.228462198742689e-07, 'min_child_weight': 3, 'reg_alpha': 0.17872983601094317, 'reg_lambda': 7.824415298034274, 'subsample': 0.3608103460466552, 'colsample_bytree': 0.226757146849718, 'tree_method': 'hist', 'n_jobs': -1}
Accuracy: 0.8096251122233801
Precision: 0.7650679945890901
F1: 0.7502027439005903
Recall: 0.7360763718341079
Balanced Accuracy:0.7961975028544466
ROC-AUC: 0.8947770381509444

[I 2026-07-29 18:15:08,963] Trial 8 finished with value: 0.8966044912565609 and parameters: {'n_estimators': 9300, 'max_depth': 19, 'learning_rate': 0.1528673668146564, 'gamma': 0.013718567303205281, 'min_child_weight': 5, 'reg_alpha': 8.00506139150923e-05, 'reg_lambda': 0.2214250092676807, 'subsample': 0.8983409295762796, 'colsample_bytree': 0.47012654665439135}. Best is trial 3 with value: 0.9070333078413493.

{'n_estimators': 9300, 'max_depth': 19, 'learning_rate': 0.1528673668146564, 'gamma': 0.013718567303205281, 'min_child_weight': 5, 'reg_alpha': 8.00506139150923e-05, 'reg_lambda': 0.2214250092676807, 'subsample': 0.8983409295762796, 'colsample_bytree': 0.47012654665439135, 'tree_method': 'hist', 'n_jobs': -1}
Accuracy: 0.8119623954400769
Precision: 0.7673644347464286
F1: 0.7538249524244856
Recall: 0.7410838654425007
Balanced Accuracy:0.7990192130674547
ROC-AUC: 0.8966044912565609

[I 2026-07-29 18:15:59,484] Trial 9 finished with value: 0.9013933995577951 and parameters: {'n_estimators': 4500, 'max_depth': 20, 'learning_rate': 0.013653043851044733, 'gamma': 2.642650788604445e-05, 'min_child_weight': 5, 'reg_alpha': 5.697035405247405e-07, 'reg_lambda': 1.7544800442961722e-06, 'subsample': 0.39730243001112114, 'colsample_bytree': 0.9424006790504464}. Best is trial 3 with value: 0.9070333078413493.

{'n_estimators': 4500, 'max_depth': 20, 'learning_rate': 0.013653043851044733, 'gamma': 2.642650788604445e-05, 'min_child_weight': 5, 'reg_alpha': 5.697035405247405e-07, 'reg_lambda': 1.7544800442961722e-06, 'subsample': 0.39730243001112114, 'colsample_bytree': 0.9424006790504464, 'tree_method': 'hist', 'n_jobs': -1}
Accuracy: 0.816055962691539
Precision: 0.7741438746711922
F1: 0.7584564585967821
Recall: 0.743601465976499
Balanced Accuracy:0.802828323678931
ROC-AUC: 0.9013933995577951

[I 2026-07-29 18:16:39,241] Trial 10 finished with value: 0.9037274460242447 and parameters: {'n_estimators': 11800, 'max_depth': 6, 'learning_rate': 0.08463816066656418, 'gamma': 0.40158722094904314, 'min_child_weight': 1, 'reg_alpha': 6.548221360866755e-08, 'reg_lambda': 1.0998672516066946e-08, 'subsample': 0.7092017752113606, 'colsample_bytree': 0.6992167675475915}. Best is trial 3 with value: 0.9070333078413493.

{'n_estimators': 11800, 'max_depth': 6, 'learning_rate': 0.08463816066656418, 'gamma': 0.40158722094904314, 'min_child_weight': 1, 'reg_alpha': 6.548221360866755e-08, 'reg_lambda': 1.0998672516066946e-08, 'subsample': 0.7092017752113606, 'colsample_bytree': 0.6992167675475915, 'tree_method': 'hist', 'n_jobs': -1}
Accuracy: 0.8090422149715953
Precision: 0.7639203798736685
F1: 0.7496276271872871
Recall: 0.7360776312640899
Balanced Accuracy:0.7957214414206044
ROC-AUC: 0.9037274460242447

[I 2026-07-29 18:17:07,415] Trial 11 finished with value: 0.9029571453847411 and parameters: {'n_estimators': 6800, 'max_depth': 16, 'learning_rate': 0.054897992941784136, 'gamma': 0.005815793157722065, 'min_child_weight': 9, 'reg_alpha': 3.489886505568537, 'reg_lambda': 0.004535876431818387, 'subsample': 0.9871066336503008, 'colsample_bytree': 0.7718610934336323}. Best is trial 3 with value: 0.9070333078413493.

{'n_estimators': 6800, 'max_depth': 16, 'learning_rate': 0.054897992941784136, 'gamma': 0.005815793157722065, 'min_child_weight': 9, 'reg_alpha': 3.489886505568537, 'reg_lambda': 0.004535876431818387, 'subsample': 0.9871066336503008, 'colsample_bytree': 0.7718610934336323, 'tree_method': 'hist', 'n_jobs': -1}
Accuracy: 0.8146916300813702
Precision: 0.7730125142937355
F1: 0.7563212755334019
Recall: 0.7405952066094885
Balanced Accuracy:0.801165958326636
ROC-AUC: 0.9029571453847411

[I 2026-07-29 18:17:32,765] Trial 12 finished with value: 0.9077859916891804 and parameters: {'n_estimators': 8100, 'max_depth': 13, 'learning_rate': 0.06459989675903716, 'gamma': 0.8855183619857552, 'min_child_weight': 8, 'reg_alpha': 6.285842598258139, 'reg_lambda': 0.004588074511302037, 'subsample': 0.838123569400284, 'colsample_bytree': 0.5200644350199716}. Best is trial 12 with value: 0.9077859916891804.

{'n_estimators': 8100, 'max_depth': 13, 'learning_rate': 0.06459989675903716, 'gamma': 0.8855183619857552, 'min_child_weight': 8, 'reg_alpha': 6.285842598258139, 'reg_lambda': 0.004588074511302037, 'subsample': 0.838123569400284, 'colsample_bytree': 0.5200644350199716, 'tree_method': 'hist', 'n_jobs': -1}
Accuracy: 0.8160578607613918
Precision: 0.7763679094034811
F1: 0.7576407780769291
Recall: 0.7400977317666024
Balanced Accuracy:0.8021923760774318
ROC-AUC: 0.9077859916891804

[I 2026-07-29 18:17:49,959] Trial 13 finished with value: 0.9026983563810804 and parameters: {'n_estimators': 4100, 'max_depth': 16, 'learning_rate': 0.07414446429283528, 'gamma': 0.8085136468493784, 'min_child_weight': 8, 'reg_alpha': 0.11449403547312947, 'reg_lambda': 0.0004949522404019331, 'subsample': 0.8063547038130096, 'colsample_bytree': 0.5225263687763206}. Best is trial 12 with value: 0.9077859916891804.

{'n_estimators': 4100, 'max_depth': 16, 'learning_rate': 0.07414446429283528, 'gamma': 0.8085136468493784, 'min_child_weight': 8, 'reg_alpha': 0.11449403547312947, 'reg_lambda': 0.0004949522404019331, 'subsample': 0.8063547038130096, 'colsample_bytree': 0.5225263687763206, 'tree_method': 'hist', 'n_jobs': -1}
Accuracy: 0.8119639138959591
Precision: 0.7679032715580659
F1: 0.7533406558053249
Recall: 0.7395851437639325
Balanced Accuracy:0.7987498449139961
ROC-AUC: 0.9026983563810804

[I 2026-07-29 18:18:34,655] Trial 14 finished with value: 0.8983504074240255 and parameters: {'n_estimators': 11700, 'max_depth': 11, 'learning_rate': 0.29074774761102246, 'gamma': 0.03365355395315258, 'min_child_weight': 1, 'reg_alpha': 0.012855036092108854, 'reg_lambda': 2.8636241668834885, 'subsample': 0.8109880960936788, 'colsample_bytree': 0.4386081365667568}. Best is trial 12 with value: 0.9077859916891804.

{'n_estimators': 11700, 'max_depth': 11, 'learning_rate': 0.29074774761102246, 'gamma': 0.03365355395315258, 'min_child_weight': 1, 'reg_alpha': 0.012855036092108854, 'reg_lambda': 2.8636241668834885, 'subsample': 0.8109880960936788, 'colsample_bytree': 0.4386081365667568, 'tree_method': 'hist', 'n_jobs': -1}
Accuracy: 0.8096243529954389
Precision: 0.76945002658894
F1: 0.7481043798044423
Recall: 0.7280399491190287
Balanced Accuracy:0.7947298558057684
ROC-AUC: 0.8983504074240255

[I 2026-07-29 18:19:34,032] Trial 15 finished with value: 0.8956243309588476 and parameters: {'n_estimators': 9200, 'max_depth': 15, 'learning_rate': 0.051696213041146424, 'gamma': 0.0014512639186029554, 'min_child_weight': 10, 'reg_alpha': 2.0583009954714706e-06, 'reg_lambda': 9.893344556364683e-05, 'subsample': 0.8044476054816884, 'colsample_bytree': 0.6107022839832308}. Best is trial 12 with value: 0.9077859916891804.

{'n_estimators': 9200, 'max_depth': 15, 'learning_rate': 0.051696213041146424, 'gamma': 0.0014512639186029554, 'min_child_weight': 10, 'reg_alpha': 2.0583009954714706e-06, 'reg_lambda': 9.893344556364683e-05, 'subsample': 0.8044476054816884, 'colsample_bytree': 0.6107022839832308, 'tree_method': 'hist', 'n_jobs': -1}
Accuracy: 0.8113787389603511
Precision: 0.7654647051349348
F1: 0.7534941540649822
Recall: 0.7420951877180388
Balanced Accuracy:0.7987299656831948
ROC-AUC: 0.8956243309588476

[I 2026-07-29 18:20:02,863] Trial 16 finished with value: 0.8984387932507591 and parameters: {'n_estimators': 5500, 'max_depth': 17, 'learning_rate': 0.12895103730009883, 'gamma': 0.12711850955657433, 'min_child_weight': 4, 'reg_alpha': 1.0014237161275117, 'reg_lambda': 0.018200329308886983, 'subsample': 0.6379206583468876, 'colsample_bytree': 0.38486611835408546}. Best is trial 12 with value: 0.9077859916891804.

{'n_estimators': 5500, 'max_depth': 17, 'learning_rate': 0.12895103730009883, 'gamma': 0.12711850955657433, 'min_child_weight': 4, 'reg_alpha': 1.0014237161275117, 'reg_lambda': 0.018200329308886983, 'subsample': 0.6379206583468876, 'colsample_bytree': 0.38486611835408546, 'tree_method': 'hist', 'n_jobs': -1}
Accuracy: 0.8111836173794869
Precision: 0.7708666565643025
F1: 0.7505895547570935
Recall: 0.7315524993387992
Balanced Accuracy:0.7966443507269073
ROC-AUC: 0.8984387932507591

[I 2026-07-29 18:20:54,162] Trial 17 finished with value: 0.8980161889704551 and parameters: {'n_estimators': 8300, 'max_depth': 10, 'learning_rate': 0.0921600508428084, 'gamma': 0.0007518122642862145, 'min_child_weight': 3, 'reg_alpha': 0.010290994712732477, 'reg_lambda': 0.038460245828251007, 'subsample': 0.8712708566091687, 'colsample_bytree': 0.6053661812829116}. Best is trial 12 with value: 0.9077859916891804.

{'n_estimators': 8300, 'max_depth': 10, 'learning_rate': 0.0921600508428084, 'gamma': 0.0007518122642862145, 'min_child_weight': 3, 'reg_alpha': 0.010290994712732477, 'reg_lambda': 0.038460245828251007, 'subsample': 0.8712708566091687, 'colsample_bytree': 0.6053661812829116, 'tree_method': 'hist', 'n_jobs': -1}
Accuracy: 0.8154715469838723
Precision: 0.7746243706325293
F1: 0.7571103787780216
Recall: 0.7406002443294165
Balanced Accuracy:0.8018059277905273
ROC-AUC: 0.8980161889704551

[I 2026-07-29 18:21:53,419] Trial 18 finished with value: 0.8959877249595841 and parameters: {'n_estimators': 11600, 'max_depth': 14, 'learning_rate': 0.05140898309218459, 'gamma': 0.126741681081657, 'min_child_weight': 8, 'reg_alpha': 2.2403292241135875e-05, 'reg_lambda': 1.283261979446528, 'subsample': 0.741744940272437, 'colsample_bytree': 0.2045720816301385}. Best is trial 12 with value: 0.9077859916891804.

{'n_estimators': 11600, 'max_depth': 14, 'learning_rate': 0.05140898309218459, 'gamma': 0.126741681081657, 'min_child_weight': 8, 'reg_alpha': 2.2403292241135875e-05, 'reg_lambda': 1.283261979446528, 'subsample': 0.741744940272437, 'colsample_bytree': 0.2045720816301385, 'tree_method': 'hist', 'n_jobs': -1}
Accuracy: 0.815081114015158
Precision: 0.7750058397822367
F1: 0.7562870779228869
Recall: 0.7385838969282503
Balanced Accuracy:0.8011147016412196
ROC-AUC: 0.8959877249595841

[I 2026-07-29 18:22:39,696] Trial 19 finished with value: 0.902923369445845 and parameters: {'n_estimators': 10600, 'max_depth': 18, 'learning_rate': 0.025633294626711975, 'gamma': 0.9792412682298086, 'min_child_weight': 6, 'reg_alpha': 0.6293296833676363, 'reg_lambda': 4.658660020883938e-05, 'subsample': 0.571368709285818, 'colsample_bytree': 0.39175095110402636}. Best is trial 12 with value: 0.9077859916891804.

{'n_estimators': 10600, 'max_depth': 18, 'learning_rate': 0.025633294626711975, 'gamma': 0.9792412682298086, 'min_child_weight': 6, 'reg_alpha': 0.6293296833676363, 'reg_lambda': 4.658660020883938e-05, 'subsample': 0.571368709285818, 'colsample_bytree': 0.39175095110402636, 'tree_method': 'hist', 'n_jobs': -1}
Accuracy: 0.8162507046584329
Precision: 0.777528467127135
F1: 0.7574218136460733
Recall: 0.7385838969282503
Balanced Accuracy:0.8020711315114946
ROC-AUC: 0.902923369445845

[I 2026-07-29 18:22:54,286] Trial 20 finished with value: 0.8996685365966932 and parameters: {'n_estimators': 3100, 'max_depth': 11, 'learning_rate': 0.21761867998688583, 'gamma': 0.07031468368641244, 'min_child_weight': 2, 'reg_alpha': 0.011372298989823617, 'reg_lambda': 1.4373825846925768e-07, 'subsample': 0.8466111623008259, 'colsample_bytree': 0.7943323662521904}. Best is trial 12 with value: 0.9077859916891804.

{'n_estimators': 3100, 'max_depth': 11, 'learning_rate': 0.21761867998688583, 'gamma': 0.07031468368641244, 'min_child_weight': 2, 'reg_alpha': 0.011372298989823617, 'reg_lambda': 1.4373825846925768e-07, 'subsample': 0.8466111623008259, 'colsample_bytree': 0.7943323662521904, 'tree_method': 'hist', 'n_jobs': -1}
Accuracy: 0.8119633444750033
Precision: 0.7678856750915106
F1: 0.7535643630286127
Recall: 0.7400863968967645
Balanced Accuracy:0.7988409818472384
ROC-AUC: 0.8996685365966932

[I 2026-07-29 18:23:20,508] Trial 21 finished with value: 0.9083827091099235 and parameters: {'n_estimators': 7800, 'max_depth': 13, 'learning_rate': 0.03585979413065538, 'gamma': 0.00025046646096832056, 'min_child_weight': 8, 'reg_alpha': 9.979812055651985, 'reg_lambda': 0.041477402642739976, 'subsample': 0.9999355054935987, 'colsample_bytree': 0.8896668801909641}. Best is trial 21 with value: 0.9083827091099235.

{'n_estimators': 7800, 'max_depth': 13, 'learning_rate': 0.03585979413065538, 'gamma': 0.00025046646096832056, 'min_child_weight': 8, 'reg_alpha': 9.979812055651985, 'reg_lambda': 0.041477402642739976, 'subsample': 0.9999355054935987, 'colsample_bytree': 0.8896668801909641, 'tree_method': 'hist', 'n_jobs': -1}
Accuracy: 0.8152783234728604
Precision: 0.7748541919541501
F1: 0.756731369530277
Recall: 0.7400939534766564
Balanced Accuracy:0.8015512585778429
ROC-AUC: 0.9083827091099235

[I 2026-07-29 18:23:48,479] Trial 22 finished with value: 0.9074745272174736 and parameters: {'n_estimators': 8300, 'max_depth': 14, 'learning_rate': 0.041530893350835506, 'gamma': 0.00030328121895575747, 'min_child_weight': 9, 'reg_alpha': 9.889074762912294, 'reg_lambda': 0.04292043031988228, 'subsample': 0.993767909683203, 'colsample_bytree': 0.799420460253015}. Best is trial 21 with value: 0.9083827091099235.

{'n_estimators': 8300, 'max_depth': 14, 'learning_rate': 0.041530893350835506, 'gamma': 0.00030328121895575747, 'min_child_weight': 9, 'reg_alpha': 9.889074762912294, 'reg_lambda': 0.04292043031988228, 'subsample': 0.993767909683203, 'colsample_bytree': 0.799420460253015, 'tree_method': 'hist', 'n_jobs': -1}
Accuracy: 0.8129400912212372
Precision: 0.7695671114106327
F1: 0.7545770781664582
Recall: 0.7405977254694525
Balanced Accuracy:0.7997333348443576
ROC-AUC: 0.9074745272174736

[I 2026-07-29 18:24:14,936] Trial 23 finished with value: 0.9071528512639576 and parameters: {'n_estimators': 7800, 'max_depth': 13, 'learning_rate': 0.06826351346238452, 'gamma': 0.0002529769078664282, 'min_child_weight': 9, 'reg_alpha': 8.337212219711775, 'reg_lambda': 0.0025778360896444555, 'subsample': 0.9987657802264519, 'colsample_bytree': 0.9926594641074807}. Best is trial 21 with value: 0.9083827091099235.

{'n_estimators': 7800, 'max_depth': 13, 'learning_rate': 0.06826351346238452, 'gamma': 0.0002529769078664282, 'min_child_weight': 9, 'reg_alpha': 8.337212219711775, 'reg_lambda': 0.0025778360896444555, 'subsample': 0.9987657802264519, 'colsample_bytree': 0.9926594641074807, 'tree_method': 'hist', 'n_jobs': -1}
Accuracy: 0.8156681870206187
Precision: 0.7744857083248069
F1: 0.7578850588382073
Recall: 0.7426039974307628
Balanced Accuracy:0.8023275576909906
ROC-AUC: 0.9071528512639576

[I 2026-07-29 18:25:14,342] Trial 24 finished with value: 0.9008749149154385 and parameters: {'n_estimators': 5800, 'max_depth': 14, 'learning_rate': 0.022768787720771236, 'gamma': 0.00017269905304170605, 'min_child_weight': 8, 'reg_alpha': 1.3108734486656786, 'reg_lambda': 0.10655308475762851, 'subsample': 0.8857450285123325, 'colsample_bytree': 0.8377611894056999}. Best is trial 21 with value: 0.9083827091099235.

{'n_estimators': 5800, 'max_depth': 14, 'learning_rate': 0.022768787720771236, 'gamma': 0.00017269905304170605, 'min_child_weight': 8, 'reg_alpha': 1.3108734486656786, 'reg_lambda': 0.10655308475762851, 'subsample': 0.8857450285123325, 'colsample_bytree': 0.8377611894056999, 'tree_method': 'hist', 'n_jobs': -1}
Accuracy: 0.814496698307491
Precision: 0.7726605758196801
F1: 0.7561694986590037
Recall: 0.7405952066094885
Balanced Accuracy:0.8010057068003101
ROC-AUC: 0.9008749149154385

[I 2026-07-29 18:26:22,150] Trial 25 finished with value: 0.8985332686892983 and parameters: {'n_estimators': 8400, 'max_depth': 12, 'learning_rate': 0.04020578382529344, 'gamma': 1.2111477093130584e-08, 'min_child_weight': 9, 'reg_alpha': 0.43917846937962696, 'reg_lambda': 0.0006111141515817035, 'subsample': 0.9949566400507287, 'colsample_bytree': 0.8564248409842157}. Best is trial 21 with value: 0.9083827091099235.

{'n_estimators': 8400, 'max_depth': 12, 'learning_rate': 0.04020578382529344, 'gamma': 1.2111477093130584e-08, 'min_child_weight': 9, 'reg_alpha': 0.43917846937962696, 'reg_lambda': 0.0006111141515817035, 'subsample': 0.9949566400507287, 'colsample_bytree': 0.8564248409842157, 'tree_method': 'hist', 'n_jobs': -1}
Accuracy: 0.8139117131788683
Precision: 0.7694954844021058
F1: 0.7566415871759316
Recall: 0.7446090099620911
Balanced Accuracy:0.8012607621555394
ROC-AUC: 0.8985332686892983

[I 2026-07-29 18:27:16,664] Trial 26 finished with value: 0.9016159951903431 and parameters: {'n_estimators': 6100, 'max_depth': 14, 'learning_rate': 0.031628190411870254, 'gamma': 0.0011958405089404981, 'min_child_weight': 7, 'reg_alpha': 3.7403336924158093, 'reg_lambda': 0.009994800641619573, 'subsample': 0.7639274224727531, 'colsample_bytree': 0.716392197268989}. Best is trial 21 with value: 0.9083827091099235.

{'n_estimators': 6100, 'max_depth': 14, 'learning_rate': 0.031628190411870254, 'gamma': 0.0011958405089404981, 'min_child_weight': 7, 'reg_alpha': 3.7403336924158093, 'reg_lambda': 0.009994800641619573, 'subsample': 0.7639274224727531, 'colsample_bytree': 0.716392197268989, 'tree_method': 'hist', 'n_jobs': -1}
Accuracy: 0.816640568206191
Precision: 0.7754600241688945
F1: 0.7590841194030349
Recall: 0.7436039848364631
Balanced Accuracy:0.8033065282221304
ROC-AUC: 0.9016159951903431

[I 2026-07-29 18:28:07,354] Trial 27 finished with value: 0.8938019979026416 and parameters: {'n_estimators': 8400, 'max_depth': 11, 'learning_rate': 0.09928343813140039, 'gamma': 0.004236476208957235, 'min_child_weight': 10, 'reg_alpha': 0.05280777915041892, 'reg_lambda': 0.0784227746654415, 'subsample': 0.9121106567970774, 'colsample_bytree': 0.637969769516244}. Best is trial 21 with value: 0.9083827091099235.

{'n_estimators': 8400, 'max_depth': 11, 'learning_rate': 0.09928343813140039, 'gamma': 0.004236476208957235, 'min_child_weight': 10, 'reg_alpha': 0.05280777915041892, 'reg_lambda': 0.0784227746654415, 'subsample': 0.9121106567970774, 'colsample_bytree': 0.637969769516244, 'tree_method': 'hist', 'n_jobs': -1}
Accuracy: 0.813522419052066
Precision: 0.7686444748305654
F1: 0.75607526741252
Recall: 0.744110275689223
Balanced Accuracy:0.8008524133146997
ROC-AUC: 0.8938019979026416

[I 2026-07-29 18:29:00,842] Trial 28 finished with value: 0.9011807991594267 and parameters: {'n_estimators': 5100, 'max_depth': 9, 'learning_rate': 0.02102151681818956, 'gamma': 0.00012495220042258855, 'min_child_weight': 9, 'reg_alpha': 2.0558486588184954, 'reg_lambda': 0.00028538875961662413, 'subsample': 0.852626812846739, 'colsample_bytree': 0.8490851136188142}. Best is trial 21 with value: 0.9083827091099235.

{'n_estimators': 5100, 'max_depth': 9, 'learning_rate': 0.02102151681818956, 'gamma': 0.00012495220042258855, 'min_child_weight': 9, 'reg_alpha': 2.0558486588184954, 'reg_lambda': 0.00028538875961662413, 'subsample': 0.852626812846739, 'colsample_bytree': 0.8490851136188142, 'tree_method': 'hist', 'n_jobs': -1}
Accuracy: 0.8141066449527475
Precision: 0.7715564632265229
F1: 0.7559185252504543
Recall: 0.7410939408823566
Balanced Accuracy:0.8007786367522947
ROC-AUC: 0.9011807991594267

[I 2026-07-29 18:30:20,026] Trial 29 finished with value: 0.8950560415406059 and parameters: {'n_estimators': 13000, 'max_depth': 15, 'learning_rate': 0.062046239505016594, 'gamma': 2.6470291805678693e-06, 'min_child_weight': 8, 'reg_alpha': 0.04479671101064814, 'reg_lambda': 0.8280600542069066, 'subsample': 0.9427148136504002, 'colsample_bytree': 0.5527310798437904}. Best is trial 21 with value: 0.9083827091099235.

{'n_estimators': 13000, 'max_depth': 15, 'learning_rate': 0.062046239505016594, 'gamma': 2.6470291805678693e-06, 'min_child_weight': 8, 'reg_alpha': 0.04479671101064814, 'reg_lambda': 0.8280600542069066, 'subsample': 0.9427148136504002, 'colsample_bytree': 0.5527310798437904, 'tree_method': 'hist', 'n_jobs': -1}
Accuracy: 0.810990963289431
Precision: 0.7666488543294255
F1: 0.7522181108691623
Recall: 0.7385914535081423
Balanced Accuracy:0.7977735150290434
ROC-AUC: 0.8950560415406059
Optimization complete!
Best Trial Accuracy Score: 0.9084
Best Hyperparameters Found:
n_estimators: 7800
max_depth: 13
learning_rate: 0.03585979413065538
gamma: 0.00025046646096832056
min_child_weight: 8
reg_alpha: 9.979812055651985
reg_lambda: 0.041477402642739976
subsample: 0.9999355054935987
colsample_bytree: 0.8896668801909641
Accuracy: 0.8158343483556637
Precision: 0.7766157740975362
F1: 0.7560638925992943
Recall: 0.7371069182389938
Balanced Accuracy:0.8013566400340096
ROC-AUC: 0.906040486639909

In [32]:
rf=RandomForest()
rf_params={'n_estimators': 600, 'max_depth': 41, 'min_samples_split': 17, 'min_samples_leaf': 6, 'max_features': 'log2', 'bootstrap': True, 'criterion': 'log_loss', 'class_weight': None, 'n_jobs': -1, 'random_state': 42}
rf.set_params(rf_params)

metrics=rf.evaluation(X_train,y_train,5)
metrics.out()

rf_params=rf.hyperparameter_tuning(X_train,y_train,20)

[I 2026-07-29 18:30:56,511] A new study created in memory with name: no-name-6eb29621-1c7e-4b81-ace7-4256ac29f4d9

Accuracy: 0.8214372716199756
Precision: 0.7882879374239677
F1: 0.761964798219479
Recall: 0.7377358490566037
Balanced Accuracy:0.8060448628980833
ROC-AUC: 0.9092226515123099

[I 2026-07-29 18:31:25,666] Trial 0 finished with value: 0.9079660402365681 and parameters: {'n_estimators': 1500, 'max_depth': 44, 'min_samples_split': 14, 'min_samples_leaf': 8, 'max_features': 'log2', 'bootstrap': False, 'criterion': 'entropy', 'class_weight': 'balanced_subsample'}. Best is trial 0 with value: 0.9079660402365681.

{'n_estimators': 1500, 'max_depth': 44, 'min_samples_split': 14, 'min_samples_leaf': 8, 'max_features': 'log2', 'bootstrap': False, 'criterion': 'entropy', 'class_weight': 'balanced_subsample', 'n_jobs': -1, 'random_state': 42}
Accuracy: 0.8141291108404385
Precision: 0.7387378676394059
F1: 0.770387112586664
Recall: 0.8050314465408805
Balanced Accuracy:0.812456081123323
ROC-AUC: 0.9079660402365681

[I 2026-07-29 18:31:59,647] Trial 1 finished with value: 0.9077572302036836 and parameters: {'n_estimators': 1100, 'max_depth': 28, 'min_samples_split': 11, 'min_samples_leaf': 5, 'max_features': 'log2', 'bootstrap': True, 'criterion': 'gini', 'class_weight': 'balanced_subsample'}. Best is trial 0 with value: 0.9079660402365681.

{'n_estimators': 1100, 'max_depth': 28, 'min_samples_split': 11, 'min_samples_leaf': 5, 'max_features': 'log2', 'bootstrap': True, 'criterion': 'gini', 'class_weight': 'balanced_subsample', 'n_jobs': -1, 'random_state': 42}
Accuracy: 0.8170523751522533
Precision: 0.7499792324993082
F1: 0.7701943040343376
Recall: 0.7918238993710693
Balanced Accuracy:0.8124129437213199
ROC-AUC: 0.9077572302036836

[I 2026-07-29 18:32:20,804] Trial 2 finished with value: 0.907219575627993 and parameters: {'n_estimators': 1100, 'max_depth': 38, 'min_samples_split': 6, 'min_samples_leaf': 6, 'max_features': 'log2', 'bootstrap': False, 'criterion': 'log_loss', 'class_weight': 'balanced_subsample'}. Best is trial 0 with value: 0.9079660402365681.

{'n_estimators': 1100, 'max_depth': 38, 'min_samples_split': 6, 'min_samples_leaf': 6, 'max_features': 'log2', 'bootstrap': False, 'criterion': 'log_loss', 'class_weight': 'balanced_subsample', 'n_jobs': -1, 'random_state': 42}
Accuracy: 0.8116930572472596
Precision: 0.7417625144885592
F1: 0.7646068968319453
Recall: 0.789308176100629
Balanced Accuracy:0.807576553259062
ROC-AUC: 0.907219575627993

[I 2026-07-29 18:32:34,733] Trial 3 finished with value: 0.9077597309226402 and parameters: {'n_estimators': 700, 'max_depth': 35, 'min_samples_split': 9, 'min_samples_leaf': 6, 'max_features': 'log2', 'bootstrap': False, 'criterion': 'log_loss', 'class_weight': None}. Best is trial 0 with value: 0.9079660402365681.

{'n_estimators': 700, 'max_depth': 35, 'min_samples_split': 9, 'min_samples_leaf': 6, 'max_features': 'log2', 'bootstrap': False, 'criterion': 'log_loss', 'class_weight': None, 'n_jobs': -1, 'random_state': 42}
Accuracy: 0.8177831912302072
Precision: 0.7828053076624755
F1: 0.7571421106461715
Recall: 0.7333333333333332
Balanced Accuracy:0.8022531477799868
ROC-AUC: 0.9077597309226402

[I 2026-07-29 18:32:46,821] Trial 4 finished with value: 0.908966327819248 and parameters: {'n_estimators': 600, 'max_depth': 10, 'min_samples_split': 12, 'min_samples_leaf': 7, 'max_features': 'log2', 'bootstrap': True, 'criterion': 'log_loss', 'class_weight': None}. Best is trial 4 with value: 0.908966327819248.

{'n_estimators': 600, 'max_depth': 10, 'min_samples_split': 12, 'min_samples_leaf': 7, 'max_features': 'log2', 'bootstrap': True, 'criterion': 'log_loss', 'class_weight': None, 'n_jobs': -1, 'random_state': 42}
Accuracy: 0.8219244823386115
Precision: 0.7862833410939265
F1: 0.7636501362546244
Recall: 0.7427672955974843
Balanced Accuracy:0.8073677432261774
ROC-AUC: 0.908966327819248

[I 2026-07-29 18:33:24,825] Trial 5 finished with value: 0.9076872100728959 and parameters: {'n_estimators': 1900, 'max_depth': 47, 'min_samples_split': 19, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'gini', 'class_weight': 'balanced'}. Best is trial 4 with value: 0.908966327819248.

{'n_estimators': 1900, 'max_depth': 47, 'min_samples_split': 19, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'gini', 'class_weight': 'balanced', 'n_jobs': -1, 'random_state': 42}
Accuracy: 0.8143727161997564
Precision: 0.7319151826843212
F1: 0.7744706899577751
Recall: 0.8226415094339623
Balanced Accuracy:0.8158933193293072
ROC-AUC: 0.9076872100728959

[I 2026-07-29 18:33:36,071] Trial 6 finished with value: 0.9083511509558999 and parameters: {'n_estimators': 400, 'max_depth': 38, 'min_samples_split': 20, 'min_samples_leaf': 10, 'max_features': 'log2', 'bootstrap': True, 'criterion': 'entropy', 'class_weight': 'balanced_subsample'}. Best is trial 4 with value: 0.908966327819248.

{'n_estimators': 400, 'max_depth': 38, 'min_samples_split': 20, 'min_samples_leaf': 10, 'max_features': 'log2', 'bootstrap': True, 'criterion': 'entropy', 'class_weight': 'balanced_subsample', 'n_jobs': -1, 'random_state': 42}
Accuracy: 0.8148599269183923
Precision: 0.7367553231766328
F1: 0.7729631258512609
Recall: 0.8132075471698114
Balanced Accuracy:0.8145560598672118
ROC-AUC: 0.9083511509558999

[I 2026-07-29 18:33:57,250] Trial 7 finished with value: 0.907219575627993 and parameters: {'n_estimators': 1100, 'max_depth': 40, 'min_samples_split': 8, 'min_samples_leaf': 6, 'max_features': 'log2', 'bootstrap': False, 'criterion': 'log_loss', 'class_weight': 'balanced_subsample'}. Best is trial 4 with value: 0.908966327819248.

{'n_estimators': 1100, 'max_depth': 40, 'min_samples_split': 8, 'min_samples_leaf': 6, 'max_features': 'log2', 'bootstrap': False, 'criterion': 'log_loss', 'class_weight': 'balanced_subsample', 'n_jobs': -1, 'random_state': 42}
Accuracy: 0.8116930572472596
Precision: 0.7417625144885592
F1: 0.7646068968319453
Recall: 0.789308176100629
Balanced Accuracy:0.807576553259062
ROC-AUC: 0.907219575627993

[I 2026-07-29 18:34:03,912] Trial 8 finished with value: 0.8277054653212798 and parameters: {'n_estimators': 100, 'max_depth': 22, 'min_samples_split': 13, 'min_samples_leaf': 6, 'max_features': None, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': 'balanced'}. Best is trial 4 with value: 0.908966327819248.

{'n_estimators': 100, 'max_depth': 22, 'min_samples_split': 13, 'min_samples_leaf': 6, 'max_features': None, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': 'balanced', 'n_jobs': -1, 'random_state': 42}
Accuracy: 0.7732034104750305
Precision: 0.6939124908404073
F1: 0.7174196119456809
Recall: 0.7433962264150943
Balanced Accuracy:0.7677219700663942
ROC-AUC: 0.8277054653212798

[I 2026-07-29 18:34:14,128] Trial 9 finished with value: 0.9081723495504959 and parameters: {'n_estimators': 500, 'max_depth': 25, 'min_samples_split': 19, 'min_samples_leaf': 7, 'max_features': 'log2', 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 4 with value: 0.908966327819248.

{'n_estimators': 500, 'max_depth': 25, 'min_samples_split': 19, 'min_samples_leaf': 7, 'max_features': 'log2', 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None, 'n_jobs': -1, 'random_state': 42}
Accuracy: 0.8185140073081607
Precision: 0.7823153238195044
F1: 0.7588848996233003
Recall: 0.7371069182389938
Balanced Accuracy:0.803543518761644
ROC-AUC: 0.9081723495504959

[I 2026-07-29 18:35:01,205] Trial 10 finished with value: 0.9025457318979206 and parameters: {'n_estimators': 2000, 'max_depth': 3, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'log_loss', 'class_weight': None}. Best is trial 4 with value: 0.908966327819248.

{'n_estimators': 2000, 'max_depth': 3, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'log_loss', 'class_weight': None, 'n_jobs': -1, 'random_state': 42}
Accuracy: 0.8185140073081607
Precision: 0.7824396268398006
F1: 0.7586573995748168
Recall: 0.7364779874213837
Balanced Accuracy:0.8034278605098966
ROC-AUC: 0.9025457318979206

[I 2026-07-29 18:35:12,630] Trial 11 finished with value: 0.9074934043537517 and parameters: {'n_estimators': 300, 'max_depth': 9, 'min_samples_split': 16, 'min_samples_leaf': 10, 'max_features': None, 'bootstrap': True, 'criterion': 'entropy', 'class_weight': None}. Best is trial 4 with value: 0.908966327819248.

{'n_estimators': 300, 'max_depth': 9, 'min_samples_split': 16, 'min_samples_leaf': 10, 'max_features': None, 'bootstrap': True, 'criterion': 'entropy', 'class_weight': None, 'n_jobs': -1, 'random_state': 42}
Accuracy: 0.8194884287454324
Precision: 0.7818185031125356
F1: 0.7612175563688794
Recall: 0.7421383647798742
Balanced Accuracy:0.8052640134038537
ROC-AUC: 0.9074934043537517

[I 2026-07-29 18:35:31,918] Trial 12 finished with value: 0.9081648473936257 and parameters: {'n_estimators': 700, 'max_depth': 16, 'min_samples_split': 20, 'min_samples_leaf': 10, 'max_features': 'log2', 'bootstrap': True, 'criterion': 'log_loss', 'class_weight': 'balanced_subsample'}. Best is trial 4 with value: 0.908966327819248.

{'n_estimators': 700, 'max_depth': 16, 'min_samples_split': 20, 'min_samples_leaf': 10, 'max_features': 'log2', 'bootstrap': True, 'criterion': 'log_loss', 'class_weight': 'balanced_subsample', 'n_jobs': -1, 'random_state': 42}
Accuracy: 0.815347137637028
Precision: 0.7371509406099535
F1: 0.7737298726919205
Recall: 0.8144654088050316
Balanced Accuracy:0.815184990684822
ROC-AUC: 0.9081648473936257

[I 2026-07-29 18:35:45,715] Trial 13 finished with value: 0.9086912487340111 and parameters: {'n_estimators': 700, 'max_depth': 31, 'min_samples_split': 16, 'min_samples_leaf': 9, 'max_features': 'log2', 'bootstrap': True, 'criterion': 'entropy', 'class_weight': None}. Best is trial 4 with value: 0.908966327819248.

{'n_estimators': 700, 'max_depth': 31, 'min_samples_split': 16, 'min_samples_leaf': 9, 'max_features': 'log2', 'bootstrap': True, 'criterion': 'entropy', 'class_weight': None, 'n_jobs': -1, 'random_state': 42}
Accuracy: 0.8207064555420219
Precision: 0.7848343696671783
F1: 0.7620434841916132
Recall: 0.740880503144654
Balanced Accuracy:0.8060267326856472
ROC-AUC: 0.9086912487340111

[I 2026-07-29 18:36:09,410] Trial 14 finished with value: 0.905486577391 and parameters: {'n_estimators': 800, 'max_depth': 13, 'min_samples_split': 16, 'min_samples_leaf': 8, 'max_features': None, 'bootstrap': True, 'criterion': 'gini', 'class_weight': None}. Best is trial 4 with value: 0.908966327819248.

{'n_estimators': 800, 'max_depth': 13, 'min_samples_split': 16, 'min_samples_leaf': 8, 'max_features': None, 'bootstrap': True, 'criterion': 'gini', 'class_weight': None, 'n_jobs': -1, 'random_state': 42}
Accuracy: 0.8158343483556638
Precision: 0.776574241656222
F1: 0.756407943016987
Recall: 0.7377358490566037
Balanced Accuracy:0.8014722982857572
ROC-AUC: 0.905486577391

[I 2026-07-29 18:36:37,807] Trial 15 finished with value: 0.9086074746489616 and parameters: {'n_estimators': 1400, 'max_depth': 31, 'min_samples_split': 16, 'min_samples_leaf': 4, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'entropy', 'class_weight': None}. Best is trial 4 with value: 0.908966327819248.

{'n_estimators': 1400, 'max_depth': 31, 'min_samples_split': 16, 'min_samples_leaf': 4, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'entropy', 'class_weight': None, 'n_jobs': -1, 'random_state': 42}
Accuracy: 0.8199756394640682
Precision: 0.785973622404086
F1: 0.760189566301854
Recall: 0.7364779874213836
Balanced Accuracy:0.8046207034522425
ROC-AUC: 0.9086074746489616

[I 2026-07-29 18:36:55,047] Trial 16 finished with value: 0.9085949710541781 and parameters: {'n_estimators': 900, 'max_depth': 17, 'min_samples_split': 12, 'min_samples_leaf': 8, 'max_features': 'log2', 'bootstrap': True, 'criterion': 'log_loss', 'class_weight': None}. Best is trial 4 with value: 0.908966327819248.

{'n_estimators': 900, 'max_depth': 17, 'min_samples_split': 12, 'min_samples_leaf': 8, 'max_features': 'log2', 'bootstrap': True, 'criterion': 'log_loss', 'class_weight': None, 'n_jobs': -1, 'random_state': 42}
Accuracy: 0.820462850182704
Precision: 0.7865622883182345
F1: 0.7608071417450272
Recall: 0.7371069182389938
Balanced Accuracy:0.8051339760181053
ROC-AUC: 0.9085949710541781

[I 2026-07-29 18:36:57,458] Trial 17 finished with value: 0.9081098315765782 and parameters: {'n_estimators': 100, 'max_depth': 50, 'min_samples_split': 10, 'min_samples_leaf': 9, 'max_features': 'log2', 'bootstrap': True, 'criterion': 'entropy', 'class_weight': 'balanced'}. Best is trial 4 with value: 0.908966327819248.

{'n_estimators': 100, 'max_depth': 50, 'min_samples_split': 10, 'min_samples_leaf': 9, 'max_features': 'log2', 'bootstrap': True, 'criterion': 'entropy', 'class_weight': 'balanced', 'n_jobs': -1, 'random_state': 42}
Accuracy: 0.8160779537149818
Precision: 0.7322983922055866
F1: 0.7774507579102762
Recall: 0.8289308176100629
Balanced Accuracy:0.8184415519461847
ROC-AUC: 0.9081098315765782

[I 2026-07-29 18:37:09,712] Trial 18 finished with value: 0.9021793765707642 and parameters: {'n_estimators': 500, 'max_depth': 3, 'min_samples_split': 6, 'min_samples_leaf': 4, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'log_loss', 'class_weight': None}. Best is trial 4 with value: 0.908966327819248.

{'n_estimators': 500, 'max_depth': 3, 'min_samples_split': 6, 'min_samples_leaf': 4, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'log_loss', 'class_weight': None, 'n_jobs': -1, 'random_state': 42}
Accuracy: 0.8165651644336176
Precision: 0.7869783913152143
F1: 0.7530306199795023
Recall: 0.7220125786163523
Balanced Accuracy:0.7991772634632456
ROC-AUC: 0.9021793765707642

[I 2026-07-29 18:37:53,948] Trial 19 finished with value: 0.9054753241556949 and parameters: {'n_estimators': 1500, 'max_depth': 22, 'min_samples_split': 14, 'min_samples_leaf': 9, 'max_features': None, 'bootstrap': True, 'criterion': 'gini', 'class_weight': None}. Best is trial 4 with value: 0.908966327819248.

{'n_estimators': 1500, 'max_depth': 22, 'min_samples_split': 14, 'min_samples_leaf': 9, 'max_features': None, 'bootstrap': True, 'criterion': 'gini', 'class_weight': None, 'n_jobs': -1, 'random_state': 42}
Accuracy: 0.8148599269183923
Precision: 0.7756477952360921
F1: 0.7548719029405966
Recall: 0.7358490566037736
Balanced Accuracy:0.8003300949022844
ROC-AUC: 0.9054753241556949
Optimization complete!
Best Trial ROC AUC: 0.9090
Best Hyperparameters Found:
n_estimators: 600
max_depth: 10
min_samples_split: 12
min_samples_leaf: 7
max_features: log2
bootstrap: True
criterion: log_loss
class_weight: None

In [33]:
mlp=MLP()
mlp_params={'hidden_layer_sizes': (128, 64, 32), 'activation': 'relu', 'solver': 'adam', 'alpha': 3.833957124267705e-05, 'learning_rate_init': 0.001020282896183049, 'batch_size': 32, 'max_iter': 500, 'early_stopping': True, 'random_state': 42}
mlp.set_params(mlp_params)

X_train_scaled,X_test_scaled=mlp.scaling(X_train,X_test)


params=mlp.hyperparameter_tuning(X_train_scaled,y_train,20)
mlp.set_params(params)

metrics=mlp.evaluation(X_train_scaled,y_train,5)
metrics.out()

[I 2026-07-29 18:37:54,042] A new study created in memory with name: no-name-e5ab15bf-a018-42e1-8eb4-0d33fc9d2c17
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 32) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128, 64) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128, 64, 32) which is of type tuple.
  optuna_warn(message)
[I 2026-07-29 18:38:04,358] Trial 0 finished with value: 0.8966752941470671 and parameters: {'hidden_layer_sizes': (128, 64), 'activation': 'logistic', 'solver': 'adam', 'alpha': 1.2996716700402713e-06, 'learning_rate_init': 0.005149147048590841, 'batch_size': 64, 'max_iter': 500}. Best is trial 0 with value: 0.8966752941470671.

{'hidden_layer_sizes': (128, 64), 'activation': 'logistic', 'solver': 'adam', 'alpha': 1.2996716700402713e-06, 'learning_rate_init': 0.005149147048590841, 'batch_size': 64, 'max_iter': 500, 'early_stopping': True, 'random_state': 42}
Accuracy: 0.809987819732034
Precision: 0.7445592289642523
F1: 0.7593313396232506
Recall: 0.7773584905660378
Balanced Accuracy:0.8039873963764583
ROC-AUC: 0.8966752941470671

c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 32) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128, 64) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128, 64, 32) which is of type tuple.
  optuna_warn(message)
[I 2026-07-29 18:38:12,327] Trial 1 finished with value: 0.8763019368068321 and parameters: {'hidden_layer_sizes': (64, 32), 'activation': 'tanh', 'solver': 'adam', 'alpha': 6.355991800785417e-05, 'learning_rate_init': 3.163876269361555e-05, 'batch_size': 64, 'max_iter': 700}. Best is trial 0 with value: 0.8966752941470671.

{'hidden_layer_sizes': (64, 32), 'activation': 'tanh', 'solver': 'adam', 'alpha': 6.355991800785417e-05, 'learning_rate_init': 3.163876269361555e-05, 'batch_size': 64, 'max_iter': 700, 'early_stopping': True, 'random_state': 42}
Accuracy: 0.7980511571254567
Precision: 0.7353695000623112
F1: 0.7411677557541095
Recall: 0.7484276729559749
Balanced Accuracy:0.7889255661002539
ROC-AUC: 0.8763019368068321

c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 32) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128, 64) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128, 64, 32) which is of type tuple.
  optuna_warn(message)
[I 2026-07-29 18:38:22,146] Trial 2 finished with value: 0.8948235117596308 and parameters: {'hidden_layer_sizes': (128, 64, 32), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0012565970481136824, 'learning_rate_init': 0.0003730708532749464, 'batch_size': 256, 'max_iter': 800}. Best is trial 0 with value: 0.8966752941470671.

{'hidden_layer_sizes': (128, 64, 32), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0012565970481136824, 'learning_rate_init': 0.0003730708532749464, 'batch_size': 256, 'max_iter': 800, 'early_stopping': True, 'random_state': 42}
Accuracy: 0.8082825822168088
Precision: 0.757075083642907
F1: 0.7501749161972644
Recall: 0.7440251572327045
Balanced Accuracy:0.7964658589344438
ROC-AUC: 0.8948235117596308

c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 32) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128, 64) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128, 64, 32) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
[I 2026-07-29 18:38:25,775] Trial 3 finished with value: 0.44328244370256453 and parameters: {'hidden_layer_sizes': (128, 64), 'activation': 'logistic', 'solver': 'sgd', 'alpha': 3.6387711960102583e-06, 'learning_rate_init': 0.0005360228065444147, 'batch_size': 256, 'max_iter': 300}. Best is trial 0 with value: 0.8966752941470671.
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 32) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128, 64) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128, 64, 32) which is of type tuple.
  optuna_warn(message)

{'hidden_layer_sizes': (128, 64), 'activation': 'logistic', 'solver': 'sgd', 'alpha': 3.6387711960102583e-06, 'learning_rate_init': 0.0005360228065444147, 'batch_size': 256, 'max_iter': 300, 'early_stopping': True, 'random_state': 42}
Accuracy: 0.6126674786845311
Precision: 0.0
F1: 0.0
Recall: 0.0
Balanced Accuracy:0.5
ROC-AUC: 0.44328244370256453

c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
[I 2026-07-29 18:38:31,022] Trial 4 finished with value: 0.5809595258636857 and parameters: {'hidden_layer_sizes': (128, 64, 32), 'activation': 'logistic', 'solver': 'sgd', 'alpha': 0.0002867624738487059, 'learning_rate_init': 0.00022525505383134406, 'batch_size': 256, 'max_iter': 800}. Best is trial 0 with value: 0.8966752941470671.

{'hidden_layer_sizes': (128, 64, 32), 'activation': 'logistic', 'solver': 'sgd', 'alpha': 0.0002867624738487059, 'learning_rate_init': 0.00022525505383134406, 'batch_size': 256, 'max_iter': 800, 'early_stopping': True, 'random_state': 42}
Accuracy: 0.620462850182704
Precision: 0.4275160081664057
F1: 0.23054688915320135
Recall: 0.15786163522012578
Balanced Accuracy:0.5353920502144367
ROC-AUC: 0.5809595258636857

c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 32) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128, 64) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128, 64, 32) which is of type tuple.
  optuna_warn(message)
[I 2026-07-29 18:38:36,485] Trial 5 finished with value: 0.8999662402940845 and parameters: {'hidden_layer_sizes': (64,), 'activation': 'tanh', 'solver': 'adam', 'alpha': 7.480261852395412e-06, 'learning_rate_init': 0.004610443270940928, 'batch_size': 32, 'max_iter': 800}. Best is trial 5 with value: 0.8999662402940845.

{'hidden_layer_sizes': (64,), 'activation': 'tanh', 'solver': 'adam', 'alpha': 7.480261852395412e-06, 'learning_rate_init': 0.004610443270940928, 'batch_size': 32, 'max_iter': 800, 'early_stopping': True, 'random_state': 42}
Accuracy: 0.8112058465286237
Precision: 0.7585978820683897
F1: 0.7552106044586784
Recall: 0.7522012578616352
Balanced Accuracy:0.8003551020918515
ROC-AUC: 0.8999662402940845

c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 32) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128, 64) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128, 64, 32) which is of type tuple.
  optuna_warn(message)
[I 2026-07-29 18:38:39,132] Trial 6 finished with value: 0.8890606049239155 and parameters: {'hidden_layer_sizes': (64,), 'activation': 'logistic', 'solver': 'adam', 'alpha': 0.0015869331487779533, 'learning_rate_init': 0.0009646396968358636, 'batch_size': 128, 'max_iter': 800}. Best is trial 5 with value: 0.8999662402940845.

{'hidden_layer_sizes': (64,), 'activation': 'logistic', 'solver': 'adam', 'alpha': 0.0015869331487779533, 'learning_rate_init': 0.0009646396968358636, 'batch_size': 128, 'max_iter': 800, 'early_stopping': True, 'random_state': 42}
Accuracy: 0.8043848964677223
Precision: 0.7574478083562529
F1: 0.7424621341957971
Recall: 0.728930817610063
Balanced Accuracy:0.7905091463795841
ROC-AUC: 0.8890606049239155

c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 32) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128, 64) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128, 64, 32) which is of type tuple.
  optuna_warn(message)
[I 2026-07-29 18:38:42,122] Trial 7 finished with value: 0.5904259974742738 and parameters: {'hidden_layer_sizes': (64,), 'activation': 'logistic', 'solver': 'sgd', 'alpha': 0.0005259530202510446, 'learning_rate_init': 2.5055599519002035e-05, 'batch_size': 32, 'max_iter': 900}. Best is trial 5 with value: 0.8999662402940845.

{'hidden_layer_sizes': (64,), 'activation': 'logistic', 'solver': 'sgd', 'alpha': 0.0005259530202510446, 'learning_rate_init': 2.5055599519002035e-05, 'batch_size': 32, 'max_iter': 900, 'early_stopping': True, 'random_state': 42}
Accuracy: 0.640925700365408
Precision: 0.6689127672535919
F1: 0.2814199363681311
Recall: 0.19056603773584904
Balanced Accuracy:0.5581060804981431
ROC-AUC: 0.5904259974742738

c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 32) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128, 64) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128, 64, 32) which is of type tuple.
  optuna_warn(message)
[I 2026-07-29 18:38:45,865] Trial 8 finished with value: 0.8830976405716644 and parameters: {'hidden_layer_sizes': (128,), 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.0001007242024501168, 'learning_rate_init': 0.0002309274872538952, 'batch_size': 64, 'max_iter': 900}. Best is trial 5 with value: 0.8999662402940845.

{'hidden_layer_sizes': (128,), 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.0001007242024501168, 'learning_rate_init': 0.0002309274872538952, 'batch_size': 64, 'max_iter': 900, 'early_stopping': True, 'random_state': 42}
Accuracy: 0.8017052375152254
Precision: 0.7349747344052986
F1: 0.748865424375486
Recall: 0.7635220125786164
Balanced Accuracy:0.7946834714980557
ROC-AUC: 0.8830976405716644

c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 32) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128, 64) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128, 64, 32) which is of type tuple.
  optuna_warn(message)
[I 2026-07-29 18:38:47,442] Trial 9 finished with value: 0.9023069132375557 and parameters: {'hidden_layer_sizes': (32,), 'activation': 'relu', 'solver': 'adam', 'alpha': 0.00017146311867992375, 'learning_rate_init': 0.004552010146185333, 'batch_size': 64, 'max_iter': 400}. Best is trial 9 with value: 0.9023069132375557.

{'hidden_layer_sizes': (32,), 'activation': 'relu', 'solver': 'adam', 'alpha': 0.00017146311867992375, 'learning_rate_init': 0.004552010146185333, 'batch_size': 64, 'max_iter': 400, 'early_stopping': True, 'random_state': 42}
Accuracy: 0.8163215590742997
Precision: 0.7735563642465365
F1: 0.75811845163146
Recall: 0.7440251572327045
Balanced Accuracy:0.8030264951173463
ROC-AUC: 0.9023069132375557

c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 32) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128, 64) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128, 64, 32) which is of type tuple.
  optuna_warn(message)
[I 2026-07-29 18:38:56,018] Trial 10 finished with value: 0.809909098865924 and parameters: {'hidden_layer_sizes': (32,), 'activation': 'relu', 'solver': 'adam', 'alpha': 0.009922978205927484, 'learning_rate_init': 1.031420006129984e-05, 'batch_size': 128, 'max_iter': 200}. Best is trial 9 with value: 0.9023069132375557.

{'hidden_layer_sizes': (32,), 'activation': 'relu', 'solver': 'adam', 'alpha': 0.009922978205927484, 'learning_rate_init': 1.031420006129984e-05, 'batch_size': 128, 'max_iter': 200, 'early_stopping': True, 'random_state': 42}
Accuracy: 0.7478684531059683
Precision: 0.7358425941609837
F1: 0.6247901951068995
Recall: 0.5465408805031446
Balanced Accuracy:0.710844992935469
ROC-AUC: 0.809909098865924

c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 32) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128, 64) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128, 64, 32) which is of type tuple.
  optuna_warn(message)
[I 2026-07-29 18:38:59,354] Trial 11 finished with value: 0.8968828538204733 and parameters: {'hidden_layer_sizes': (32,), 'activation': 'relu', 'solver': 'adam', 'alpha': 1.4582241981084176e-05, 'learning_rate_init': 0.00832134369685739, 'batch_size': 32, 'max_iter': 500}. Best is trial 9 with value: 0.9023069132375557.

{'hidden_layer_sizes': (32,), 'activation': 'relu', 'solver': 'adam', 'alpha': 1.4582241981084176e-05, 'learning_rate_init': 0.00832134369685739, 'batch_size': 32, 'max_iter': 500, 'early_stopping': True, 'random_state': 42}
Accuracy: 0.8095006090133982
Precision: 0.7610883704879383
F1: 0.7510008478075831
Recall: 0.7415094339622641
Balanced Accuracy:0.7969972617127424
ROC-AUC: 0.8968828538204733

c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 32) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128, 64) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128, 64, 32) which is of type tuple.
  optuna_warn(message)
[I 2026-07-29 18:39:02,271] Trial 12 finished with value: 0.8997049151631094 and parameters: {'hidden_layer_sizes': (32,), 'activation': 'relu', 'solver': 'adam', 'alpha': 2.1408916939999107e-05, 'learning_rate_init': 0.0023354435166715337, 'batch_size': 32, 'max_iter': 500}. Best is trial 9 with value: 0.9023069132375557.

{'hidden_layer_sizes': (32,), 'activation': 'relu', 'solver': 'adam', 'alpha': 2.1408916939999107e-05, 'learning_rate_init': 0.0023354435166715337, 'batch_size': 32, 'max_iter': 500, 'early_stopping': True, 'random_state': 42}
Accuracy: 0.8197320341047505
Precision: 0.7746272894907105
F1: 0.7641066964024346
Recall: 0.7547169811320755
Balanced Accuracy:0.8077759855958588
ROC-AUC: 0.8997049151631094

c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 32) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128, 64) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128, 64, 32) which is of type tuple.
  optuna_warn(message)
[I 2026-07-29 18:39:05,388] Trial 13 finished with value: 0.9012366055240882 and parameters: {'hidden_layer_sizes': (64,), 'activation': 'relu', 'solver': 'adam', 'alpha': 1.1725961633621213e-05, 'learning_rate_init': 0.0024871551292683027, 'batch_size': 32, 'max_iter': 1000}. Best is trial 9 with value: 0.9023069132375557.

{'hidden_layer_sizes': (64,), 'activation': 'relu', 'solver': 'adam', 'alpha': 1.1725961633621213e-05, 'learning_rate_init': 0.0024871551292683027, 'batch_size': 32, 'max_iter': 1000, 'early_stopping': True, 'random_state': 42}
Accuracy: 0.8148599269183923
Precision: 0.7653839064331319
F1: 0.7588148224095702
Recall: 0.7534591194968554
Balanced Accuracy:0.8035685259512111
ROC-AUC: 0.9012366055240882

c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 32) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128, 64) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128, 64, 32) which is of type tuple.
  optuna_warn(message)
[I 2026-07-29 18:39:08,102] Trial 14 finished with value: 0.9020018255248384 and parameters: {'hidden_layer_sizes': (64, 32), 'activation': 'relu', 'solver': 'adam', 'alpha': 4.492058213957109e-05, 'learning_rate_init': 0.001599573970398692, 'batch_size': 64, 'max_iter': 1000}. Best is trial 9 with value: 0.9023069132375557.

{'hidden_layer_sizes': (64, 32), 'activation': 'relu', 'solver': 'adam', 'alpha': 4.492058213957109e-05, 'learning_rate_init': 0.001599573970398692, 'batch_size': 64, 'max_iter': 1000, 'early_stopping': True, 'random_state': 42}
Accuracy: 0.8129110840438489
Precision: 0.7716644315485578
F1: 0.7529915304246144
Recall: 0.7364779874213837
Balanced Accuracy:0.7988552958975705
ROC-AUC: 0.9020018255248384

c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 32) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128, 64) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128, 64, 32) which is of type tuple.
  optuna_warn(message)
[I 2026-07-29 18:39:10,986] Trial 15 finished with value: 0.9017017392500343 and parameters: {'hidden_layer_sizes': (128,), 'activation': 'relu', 'solver': 'adam', 'alpha': 9.500810985171762e-05, 'learning_rate_init': 0.0014988745738021732, 'batch_size': 64, 'max_iter': 600}. Best is trial 9 with value: 0.9023069132375557.

{'hidden_layer_sizes': (128,), 'activation': 'relu', 'solver': 'adam', 'alpha': 9.500810985171762e-05, 'learning_rate_init': 0.0014988745738021732, 'batch_size': 64, 'max_iter': 600, 'early_stopping': True, 'random_state': 42}
Accuracy: 0.8112058465286236
Precision: 0.7648991019839695
F1: 0.7531216895227967
Recall: 0.7427672955974842
Balanced Accuracy:0.7986202283156407
ROC-AUC: 0.9017017392500343

c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 32) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128, 64) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128, 64, 32) which is of type tuple.
  optuna_warn(message)
[I 2026-07-29 18:39:14,523] Trial 16 finished with value: 0.901164084674344 and parameters: {'hidden_layer_sizes': (64, 32), 'activation': 'relu', 'solver': 'adam', 'alpha': 4.6164856719722034e-05, 'learning_rate_init': 0.000850228730701586, 'batch_size': 64, 'max_iter': 300}. Best is trial 9 with value: 0.9023069132375557.

{'hidden_layer_sizes': (64, 32), 'activation': 'relu', 'solver': 'adam', 'alpha': 4.6164856719722034e-05, 'learning_rate_init': 0.000850228730701586, 'batch_size': 64, 'max_iter': 300, 'early_stopping': True, 'random_state': 42}
Accuracy: 0.8155907429963459
Precision: 0.7703059548737717
F1: 0.7589436497468858
Recall: 0.749685534591195
Balanced Accuracy:0.8034709979118997
ROC-AUC: 0.901164084674344

c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 32) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128, 64) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128, 64, 32) which is of type tuple.
  optuna_warn(message)
[I 2026-07-29 18:39:17,712] Trial 17 finished with value: 0.9022031334008528 and parameters: {'hidden_layer_sizes': (64, 32), 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0002477601173421603, 'learning_rate_init': 0.009647667222166813, 'batch_size': 64, 'max_iter': 1000}. Best is trial 9 with value: 0.9023069132375557.

{'hidden_layer_sizes': (64, 32), 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0002477601173421603, 'learning_rate_init': 0.009647667222166813, 'batch_size': 64, 'max_iter': 1000, 'early_stopping': True, 'random_state': 42}
Accuracy: 0.8124238733252133
Precision: 0.7787024481514416
F1: 0.7480399859125629
Recall: 0.720754716981132
Balanced Accuracy:0.7955662252897708
ROC-AUC: 0.9022031334008528

c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 32) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128, 64) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128, 64, 32) which is of type tuple.
  optuna_warn(message)
[I 2026-07-29 18:39:19,146] Trial 18 finished with value: 0.8964714855520961 and parameters: {'hidden_layer_sizes': (32,), 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.0002500401340247349, 'learning_rate_init': 0.007641395239832474, 'batch_size': 64, 'max_iter': 400}. Best is trial 9 with value: 0.9023069132375557.

{'hidden_layer_sizes': (32,), 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.0002500401340247349, 'learning_rate_init': 0.007641395239832474, 'batch_size': 64, 'max_iter': 400, 'early_stopping': True, 'random_state': 42}
Accuracy: 0.8172959805115714
Precision: 0.767178836376055
F1: 0.7631459449924286
Recall: 0.759748427672956
Balanced Accuracy:0.8067131800392613
ROC-AUC: 0.8964714855520961

c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 32) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128, 64) which is of type tuple.
  optuna_warn(message)
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\optuna\distributions.py:502: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128, 64, 32) which is of type tuple.
  optuna_warn(message)
[I 2026-07-29 18:39:22,161] Trial 19 finished with value: 0.9019042974855271 and parameters: {'hidden_layer_sizes': (64, 32), 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0029731951659696327, 'learning_rate_init': 0.003512320366088238, 'batch_size': 64, 'max_iter': 200}. Best is trial 9 with value: 0.9023069132375557.

{'hidden_layer_sizes': (64, 32), 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0029731951659696327, 'learning_rate_init': 0.003512320366088238, 'batch_size': 64, 'max_iter': 200, 'early_stopping': True, 'random_state': 42}
Accuracy: 0.8124238733252132
Precision: 0.7726856290989442
F1: 0.751161721508643
Recall: 0.7314465408805032
Balanced Accuracy:0.7975324155694763
ROC-AUC: 0.9019042974855271
Optimization complete!
Best Trial ROC AUC: 0.9023
Best Hyperparameters Found:
hidden_layer_sizes: (32,)
activation: relu
solver: adam
alpha: 0.00017146311867992375
learning_rate_init: 0.004552010146185333
batch_size: 64
max_iter: 400
Accuracy: 0.8163215590742997
Precision: 0.7735563642465365
F1: 0.75811845163146
Recall: 0.7440251572327045
Balanced Accuracy:0.8030264951173463
ROC-AUC: 0.9023069132375557

In [34]:
knn=KNN()
knn_params={'n_neighbors': 50, 'weights': 'uniform', 'metric': 'manhattan', 'p': 3, 'algorithm': 'auto', 'leaf_size': 34, 'n_jobs': -1}
knn.set_params(knn_params)

metrics=knn.evaluation(X_train_scaled,y_train,5)
metrics.out()

parameters=knn.hyperparameter_tuning(X_train_scaled,y_train,20)

[I 2026-07-29 18:39:24,591] A new study created in memory with name: no-name-3a0cbfc3-b7d8-45ba-b93c-2d5d62dea92f

Accuracy: 0.8131546894031668
Precision: 0.7922708545984385
F1: 0.744026440471727
Recall: 0.7018867924528303
Balanced Accuracy:0.7926928992085224
ROC-AUC: 0.8994129562249146

[I 2026-07-29 18:39:24,995] Trial 0 finished with value: 0.8925278517573801 and parameters: {'n_neighbors': 18, 'weights': 'uniform', 'metric': 'manhattan', 'p': 5, 'algorithm': 'brute', 'leaf_size': 72}. Best is trial 0 with value: 0.8925278517573801.

{'n_neighbors': 18, 'weights': 'uniform', 'metric': 'manhattan', 'p': 5, 'algorithm': 'brute', 'leaf_size': 72, 'n_jobs': -1}
Accuracy: 0.8014616321559075
Precision: 0.7816412959424373
F1: 0.7251367216771321
Recall: 0.6767295597484276
Balanced Accuracy:0.7785238255998599
ROC-AUC: 0.8925278517573801

[I 2026-07-29 18:39:25,423] Trial 1 finished with value: 0.8991866411593332 and parameters: {'n_neighbors': 32, 'weights': 'uniform', 'metric': 'manhattan', 'p': 1, 'algorithm': 'brute', 'leaf_size': 87}. Best is trial 1 with value: 0.8991866411593332.

{'n_neighbors': 32, 'weights': 'uniform', 'metric': 'manhattan', 'p': 1, 'algorithm': 'brute', 'leaf_size': 87, 'n_jobs': -1}
Accuracy: 0.8133982947624847
Precision: 0.79618109943503
F1: 0.7429782771972055
Recall: 0.6968553459119498
Balanced Accuracy:0.7919664403516011
ROC-AUC: 0.8991866411593332

[I 2026-07-29 18:39:26,331] Trial 2 finished with value: 0.9005951711116946 and parameters: {'n_neighbors': 28, 'weights': 'uniform', 'metric': 'minkowski', 'p': 2, 'algorithm': 'kd_tree', 'leaf_size': 12}. Best is trial 2 with value: 0.9005951711116946.

{'n_neighbors': 28, 'weights': 'uniform', 'metric': 'minkowski', 'p': 2, 'algorithm': 'kd_tree', 'leaf_size': 12, 'n_jobs': -1}
Accuracy: 0.8121802679658952
Precision: 0.7907750121559366
F1: 0.7429989119588751
Recall: 0.7012578616352201
Balanced Accuracy:0.7917820123285443
ROC-AUC: 0.9005951711116946

[I 2026-07-29 18:39:27,185] Trial 3 finished with value: 0.9002957100166299 and parameters: {'n_neighbors': 44, 'weights': 'uniform', 'metric': 'euclidean', 'p': 1, 'algorithm': 'kd_tree', 'leaf_size': 39}. Best is trial 2 with value: 0.9005951711116946.

{'n_neighbors': 44, 'weights': 'uniform', 'metric': 'euclidean', 'p': 1, 'algorithm': 'kd_tree', 'leaf_size': 39, 'n_jobs': -1}
Accuracy: 0.8136419001218027
Precision: 0.7904291247028168
F1: 0.7456689996412704
Recall: 0.7062893081761005
Balanced Accuracy:0.7939001212848693
ROC-AUC: 0.9002957100166299

[I 2026-07-29 18:39:28,098] Trial 4 finished with value: 0.8902665766407842 and parameters: {'n_neighbors': 14, 'weights': 'uniform', 'metric': 'manhattan', 'p': 5, 'algorithm': 'kd_tree', 'leaf_size': 99}. Best is trial 2 with value: 0.9005951711116946.

{'n_neighbors': 14, 'weights': 'uniform', 'metric': 'manhattan', 'p': 5, 'algorithm': 'kd_tree', 'leaf_size': 99, 'n_jobs': -1}
Accuracy: 0.8
Precision: 0.7831314857067266
F1: 0.7215650062375258
Recall: 0.6691823899371069
Balanced Accuracy:0.7759430836365454
ROC-AUC: 0.8902665766407842

[I 2026-07-29 18:39:28,537] Trial 5 finished with value: 0.8991141203095889 and parameters: {'n_neighbors': 37, 'weights': 'uniform', 'metric': 'manhattan', 'p': 3, 'algorithm': 'brute', 'leaf_size': 94}. Best is trial 2 with value: 0.9005951711116946.

{'n_neighbors': 37, 'weights': 'uniform', 'metric': 'manhattan', 'p': 3, 'algorithm': 'brute', 'leaf_size': 94, 'n_jobs': -1}
Accuracy: 0.8131546894031668
Precision: 0.7810535277146753
F1: 0.7487244590919827
Recall: 0.7194968553459119
Balanced Accuracy:0.7959313302574491
ROC-AUC: 0.8991141203095889

[I 2026-07-29 18:39:28,894] Trial 6 finished with value: 0.9003957387748978 and parameters: {'n_neighbors': 28, 'weights': 'distance', 'metric': 'euclidean', 'p': 1, 'algorithm': 'brute', 'leaf_size': 71}. Best is trial 2 with value: 0.9005951711116946.

{'n_neighbors': 28, 'weights': 'distance', 'metric': 'euclidean', 'p': 1, 'algorithm': 'brute', 'leaf_size': 71, 'n_jobs': -1}
Accuracy: 0.8138855054811206
Precision: 0.7814516923365774
F1: 0.7501998842439112
Recall: 0.7220125786163523
Balanced Accuracy:0.7969903847356115
ROC-AUC: 0.9003957387748978

[I 2026-07-29 18:39:29,782] Trial 7 finished with value: 0.8999162259149506 and parameters: {'n_neighbors': 30, 'weights': 'uniform', 'metric': 'euclidean', 'p': 4, 'algorithm': 'kd_tree', 'leaf_size': 50}. Best is trial 2 with value: 0.9005951711116946.

{'n_neighbors': 30, 'weights': 'uniform', 'metric': 'euclidean', 'p': 4, 'algorithm': 'kd_tree', 'leaf_size': 50, 'n_jobs': -1}
Accuracy: 0.8097442143727163
Precision: 0.7908636364049286
F1: 0.7379156947356514
Recall: 0.6924528301886792
Balanced Accuracy:0.7881747252335046
ROC-AUC: 0.8999162259149506

[I 2026-07-29 18:39:30,802] Trial 8 finished with value: 0.8991491303749829 and parameters: {'n_neighbors': 41, 'weights': 'uniform', 'metric': 'manhattan', 'p': 2, 'algorithm': 'kd_tree', 'leaf_size': 20}. Best is trial 2 with value: 0.9005951711116946.

{'n_neighbors': 41, 'weights': 'uniform', 'metric': 'manhattan', 'p': 2, 'algorithm': 'kd_tree', 'leaf_size': 20, 'n_jobs': -1}
Accuracy: 0.8116930572472596
Precision: 0.7795302696418908
F1: 0.7463389917994834
Recall: 0.7163522012578616
Balanced Accuracy:0.7941601960563662
ROC-AUC: 0.8991491303749829

[I 2026-07-29 18:39:31,232] Trial 9 finished with value: 0.8991141203095889 and parameters: {'n_neighbors': 37, 'weights': 'uniform', 'metric': 'manhattan', 'p': 3, 'algorithm': 'brute', 'leaf_size': 65}. Best is trial 2 with value: 0.9005951711116946.

{'n_neighbors': 37, 'weights': 'uniform', 'metric': 'manhattan', 'p': 3, 'algorithm': 'brute', 'leaf_size': 65, 'n_jobs': -1}
Accuracy: 0.8131546894031668
Precision: 0.7810535277146753
F1: 0.7487244590919827
Recall: 0.7194968553459119
Balanced Accuracy:0.7959313302574491
ROC-AUC: 0.8991141203095889

[I 2026-07-29 18:39:33,929] Trial 10 finished with value: 0.8450041887042525 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'metric': 'minkowski', 'p': 3, 'algorithm': 'ball_tree', 'leaf_size': 10}. Best is trial 2 with value: 0.9005951711116946.

{'n_neighbors': 3, 'weights': 'distance', 'metric': 'minkowski', 'p': 3, 'algorithm': 'ball_tree', 'leaf_size': 10, 'n_jobs': -1}
Accuracy: 0.7880633373934226
Precision: 0.7404122142704346
F1: 0.7185752579691712
Recall: 0.6981132075471697
Balanced Accuracy:0.7715218125210999
ROC-AUC: 0.8450041887042525

[I 2026-07-29 18:39:34,229] Trial 11 finished with value: 0.8982369931355265 and parameters: {'n_neighbors': 23, 'weights': 'distance', 'metric': 'minkowski', 'p': 2, 'algorithm': 'auto', 'leaf_size': 37}. Best is trial 2 with value: 0.9005951711116946.

{'n_neighbors': 23, 'weights': 'distance', 'metric': 'minkowski', 'p': 2, 'algorithm': 'auto', 'leaf_size': 37, 'n_jobs': -1}
Accuracy: 0.8112058465286237
Precision: 0.7775461120238478
F1: 0.7464471652732483
Recall: 0.7182389937106918
Balanced Accuracy:0.7941095564974929
ROC-AUC: 0.8982369931355265

[I 2026-07-29 18:39:35,209] Trial 12 finished with value: 0.9003200920264577 and parameters: {'n_neighbors': 28, 'weights': 'distance', 'metric': 'minkowski', 'p': 2, 'algorithm': 'ball_tree', 'leaf_size': 66}. Best is trial 2 with value: 0.9005951711116946.

{'n_neighbors': 28, 'weights': 'distance', 'metric': 'minkowski', 'p': 2, 'algorithm': 'ball_tree', 'leaf_size': 66, 'n_jobs': -1}
Accuracy: 0.8138855054811206
Precision: 0.7814516923365774
F1: 0.7501998842439112
Recall: 0.7220125786163523
Balanced Accuracy:0.7969903847356115
ROC-AUC: 0.9003200920264577

[I 2026-07-29 18:39:35,576] Trial 13 finished with value: 0.900267576928367 and parameters: {'n_neighbors': 48, 'weights': 'distance', 'metric': 'euclidean', 'p': 1, 'algorithm': 'auto', 'leaf_size': 31}. Best is trial 2 with value: 0.9005951711116946.

{'n_neighbors': 48, 'weights': 'distance', 'metric': 'euclidean', 'p': 1, 'algorithm': 'auto', 'leaf_size': 31, 'n_jobs': -1}
Accuracy: 0.815347137637028
Precision: 0.7856379893736515
F1: 0.7514151284102806
Recall: 0.720754716981132
Balanced Accuracy:0.7979519111744626
ROC-AUC: 0.900267576928367

[I 2026-07-29 18:39:36,467] Trial 14 finished with value: 0.8970747840004002 and parameters: {'n_neighbors': 21, 'weights': 'distance', 'metric': 'minkowski', 'p': 2, 'algorithm': 'kd_tree', 'leaf_size': 52}. Best is trial 2 with value: 0.9005951711116946.

{'n_neighbors': 21, 'weights': 'distance', 'metric': 'minkowski', 'p': 2, 'algorithm': 'kd_tree', 'leaf_size': 52, 'n_jobs': -1}
Accuracy: 0.8063337393422655
Precision: 0.7694593386146764
F1: 0.7404966610691439
Recall: 0.7138364779874213
Balanced Accuracy:0.7893238055941083
ROC-AUC: 0.8970747840004002

[I 2026-07-29 18:39:36,763] Trial 15 finished with value: 0.8904747614939295 and parameters: {'n_neighbors': 13, 'weights': 'distance', 'metric': 'euclidean', 'p': 1, 'algorithm': 'brute', 'leaf_size': 84}. Best is trial 2 with value: 0.9005951711116946.

{'n_neighbors': 13, 'weights': 'distance', 'metric': 'euclidean', 'p': 1, 'algorithm': 'brute', 'leaf_size': 84, 'n_jobs': -1}
Accuracy: 0.799756394640682
Precision: 0.7589542808450636
F1: 0.7324435566985482
Recall: 0.7081761006289307
Balanced Accuracy:0.7829150880878253
ROC-AUC: 0.8904747614939295

[I 2026-07-29 18:39:37,084] Trial 16 finished with value: 0.8990165922702777 and parameters: {'n_neighbors': 25, 'weights': 'distance', 'metric': 'minkowski', 'p': 2, 'algorithm': 'auto', 'leaf_size': 51}. Best is trial 2 with value: 0.9005951711116946.

{'n_neighbors': 25, 'weights': 'distance', 'metric': 'minkowski', 'p': 2, 'algorithm': 'auto', 'leaf_size': 51, 'n_jobs': -1}
Accuracy: 0.8107186358099879
Precision: 0.7751052067678579
F1: 0.7466737548246657
Recall: 0.7207547169811319
Balanced Accuracy:0.7941745751903672
ROC-AUC: 0.8990165922702777

[I 2026-07-29 18:39:38,281] Trial 17 finished with value: 0.8998043187416382 and parameters: {'n_neighbors': 34, 'weights': 'distance', 'metric': 'euclidean', 'p': 1, 'algorithm': 'ball_tree', 'leaf_size': 22}. Best is trial 2 with value: 0.9005951711116946.

{'n_neighbors': 34, 'weights': 'distance', 'metric': 'euclidean', 'p': 1, 'algorithm': 'ball_tree', 'leaf_size': 22, 'n_jobs': -1}
Accuracy: 0.8146163215590743
Precision: 0.7818107621376564
F1: 0.7513939828168541
Recall: 0.7238993710691823
Balanced Accuracy:0.7979337809620266
ROC-AUC: 0.8998043187416382

[I 2026-07-29 18:39:39,080] Trial 18 finished with value: 0.873983770333971 and parameters: {'n_neighbors': 6, 'weights': 'uniform', 'metric': 'euclidean', 'p': 3, 'algorithm': 'kd_tree', 'leaf_size': 76}. Best is trial 2 with value: 0.9005951711116946.

{'n_neighbors': 6, 'weights': 'uniform', 'metric': 'euclidean', 'p': 3, 'algorithm': 'kd_tree', 'leaf_size': 76, 'n_jobs': -1}
Accuracy: 0.7941534713763703
Precision: 0.7969768885819378
F1: 0.7033229771618362
Recall: 0.6295597484276729
Balanced Accuracy:0.763885242007077
ROC-AUC: 0.873983770333971

[I 2026-07-29 18:39:42,675] Trial 19 finished with value: 0.8969610012878704 and parameters: {'n_neighbors': 26, 'weights': 'distance', 'metric': 'minkowski', 'p': 4, 'algorithm': 'brute', 'leaf_size': 13}. Best is trial 2 with value: 0.9005951711116946.

{'n_neighbors': 26, 'weights': 'distance', 'metric': 'minkowski', 'p': 4, 'algorithm': 'brute', 'leaf_size': 13, 'n_jobs': -1}
Accuracy: 0.8051157125456759
Precision: 0.7674817634472039
F1: 0.7389884575941778
Recall: 0.7132075471698113
Balanced Accuracy:0.7882141115570727
ROC-AUC: 0.8969610012878704
Optimization complete!
Best Trial ROC AUC: 0.9006
Best Hyperparameters Found:
n_neighbors: 28
weights: uniform
metric: minkowski
p: 2
algorithm: kd_tree
leaf_size: 12

In [35]:
ensemble=[xgb,rf,mlp,knn]
X_train_copy=X_train_scaled.copy()
X_test_copy=X_test_scaled.copy()
for model in ensemble:
    X_train_scaled[f'OOF_{type(model).__name__}'],X_test_scaled[f'OOF_{type(model).__name__}']=model.oof(X_train,y_train,X_test,type(model).__name__,10)

XGBoost fold 1/10 done
XGBoost fold 2/10 done
XGBoost fold 3/10 done
XGBoost fold 4/10 done
XGBoost fold 5/10 done
XGBoost fold 6/10 done
XGBoost fold 7/10 done
XGBoost fold 8/10 done
XGBoost fold 9/10 done
XGBoost fold 10/10 done
RandomForest fold 1/10 done
RandomForest fold 2/10 done
RandomForest fold 3/10 done
RandomForest fold 4/10 done
RandomForest fold 5/10 done
RandomForest fold 6/10 done
RandomForest fold 7/10 done
RandomForest fold 8/10 done
RandomForest fold 9/10 done
RandomForest fold 10/10 done
MLP fold 1/10 done
MLP fold 2/10 done
MLP fold 3/10 done
MLP fold 4/10 done
MLP fold 5/10 done
MLP fold 6/10 done
MLP fold 7/10 done
MLP fold 8/10 done
MLP fold 9/10 done
MLP fold 10/10 done
KNN fold 1/10 done
KNN fold 2/10 done
KNN fold 3/10 done
KNN fold 4/10 done
KNN fold 5/10 done
KNN fold 6/10 done
KNN fold 7/10 done
KNN fold 8/10 done
KNN fold 9/10 done
KNN fold 10/10 done

In [36]:

X_train_scaled.tail(2)

,age,bmi,chol,tg,hdl,ldl,cr,bun,anomaly_score,lipids,...,Cluster 1,Cluster 2,Cluster 3,Cluster 4,Cluster 5,gender,OOF_XGBoost,OOF_RandomForest,OOF_MLP,OOF_KNN
4103,0.790873,-0.895603,0.626755,1.696870,0.535016,-0.099447,2.336310,0.517578,-0.293922,0.109642,...,-0.117481,0.466795,-0.064501,-0.966795,0.443252,1,0.572708,0.468233,0.288082,0.366685
4104,0.218595,1.521877,-0.146288,-1.075674,-0.953911,-1.881852,-1.560401,1.062221,-0.293922,1.562009,...,2.987245,-3.047979,2.338073,2.510651,1.679856,0,0.961586,0.990845,0.961486,0.760132

In [37]:
meta_x_model=LogisticRegression(    penalty='l2',
    C=0.1,
    solver='lbfgs',
    max_iter=5000,
    class_weight='balanced',   # or None
    random_state=42,
    n_jobs=-1)

In [38]:
X_train_scaled.columns

Index(['age', 'bmi', 'chol', 'tg', 'hdl', 'ldl', 'cr', 'bun', 'anomaly_score',
       'lipids', 'Age_x_BMI', 'HDL_x_LDL', 'BMI/LDL', 'BMI/HDL+LDL',
       'bun_x_cr', 'chol/ldl', 'cluster_labels', 'Cluster 0', 'Cluster 1',
       'Cluster 2', 'Cluster 3', 'Cluster 4', 'Cluster 5', 'gender',
       'OOF_XGBoost', 'OOF_RandomForest', 'OOF_MLP', 'OOF_KNN'],
      dtype='str')

In [39]:
meta_x_model.fit(X_train_scaled,y_train)
lr_proba=meta_x_model.predict_proba(X_test_scaled)
preds=meta_x_model.predict(X_test_scaled)

c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\Lenovo\anaconda3\envs\Diabetes\Lib\site-packages\sklearn\linear_model\_logistic.py:1457: FutureWarning: 'n_jobs' has no effect since 1.8 and will be removed in 1.10. You provided 'n_jobs=-1', please leave it unspecified.
  warnings.warn(msg, category=FutureWarning)

In [40]:

def measure(y_pred: np.ndarray, y_proba: np.ndarray, y_real: np.ndarray) -> dict:
    metrics = {}
    metrics['accuracy'] = accuracy_score(y_real, y_pred)
    metrics['balanced']=balanced_accuracy_score(y_real,y_pred)
    metrics['precision'] = precision_score(y_real, y_pred, average='macro')
    metrics['f1'] = f1_score(y_real, y_pred, average='macro')
    metrics['recall'] = recall_score(y_real, y_pred, average='macro')
    metrics['roc_auc'] = roc_auc_score(y_real, y_proba[:,1], average='macro')
    return metrics

In [41]:
def compare(base: dict, meta: dict):
    for key in base:
        diff = meta[key] - base[key]
        symbol = "↑" if diff > 0 else ("↓" if diff < 0 else "=")
        print(f"{key}: base={base[key]:.4f} meta={meta[key]:.4f} {symbol} ({diff:+.4f})")

In [47]:
logistic_regression_metrics=measure(preds,lr_proba,y_test)
print(logistic_regression_metrics)
# {'accuracy': 0.8383641674780915, 'balanced': 0.8406224152191895, 'precision': 0.8300567967262891, 'f1': 0.8335305789255778, 'recall': 0.8406224152191895, 'roc_auc': 0.9163286568683591}

{'accuracy': 0.8383641674780915, 'balanced': 0.841501240694789, 'precision': 0.8302720539031313, 'f1': 0.8337552462827453, 'recall': 0.841501240694789, 'roc_auc': 0.9165752051918306}

In [43]:
for model in ensemble:
    if model.__class__.__name__ in ["XGBoost", "RandomForest"]:
        model.train(X_train,y_train)
    else:
        model.train(X_train_copy,y_train)

In [44]:
for model in ensemble:
    print(f'Model:{model}')
    if model.__class__.__name__ in ["XGBoost", "RandomForest"]:
        predictions=model.predict(X_test)
        proba=model.predict_proba(X_test)
        vals=measure(predictions,proba,y_test)
        compare(vals,logistic_regression_metrics)
    else:
        predictions=model.predict(X_test_copy)
        proba=model.predict_proba(X_test_copy)
        vals=measure(predictions,proba,y_test)
        compare(vals,logistic_regression_metrics)

Model:<modeling.XGBoost.XGBoost object at 0x000001D7CF63F110>
accuracy: base=0.8403 meta=0.8384 ↓ (-0.0019)
balanced: base=0.8312 meta=0.8415 ↑ (+0.0103)
precision: base=0.8330 meta=0.8303 ↓ (-0.0028)
f1: base=0.8321 meta=0.8338 ↑ (+0.0016)
recall: base=0.8312 meta=0.8415 ↑ (+0.0103)
roc_auc: base=0.9194 meta=0.9166 ↓ (-0.0028)
Model:<modeling.RandomForest.RandomForest object at 0x000001D7CF78A710>
accuracy: base=0.8374 meta=0.8384 ↑ (+0.0010)
balanced: base=0.8271 meta=0.8415 ↑ (+0.0144)
precision: base=0.8304 meta=0.8303 ↓ (-0.0002)
f1: base=0.8286 meta=0.8338 ↑ (+0.0051)
recall: base=0.8271 meta=0.8415 ↑ (+0.0144)
roc_auc: base=0.9190 meta=0.9166 ↓ (-0.0024)
Model:<modeling.MLP.MLP object at 0x000001D7CF78BB10>
accuracy: base=0.8257 meta=0.8384 ↑ (+0.0127)
balanced: base=0.8131 meta=0.8415 ↑ (+0.0284)
precision: base=0.8189 meta=0.8303 ↑ (+0.0114)
f1: base=0.8156 meta=0.8338 ↑ (+0.0181)
recall: base=0.8131 meta=0.8415 ↑ (+0.0284)
roc_auc: base=0.9091 meta=0.9166 ↑ (+0.0075)
Model:<modeling.KNN.KNN object at 0x000001D7CF78BED0>
accuracy: base=0.8140 meta=0.8384 ↑ (+0.0243)
balanced: base=0.7995 meta=0.8415 ↑ (+0.0420)
precision: base=0.8070 meta=0.8303 ↑ (+0.0233)
f1: base=0.8027 meta=0.8338 ↑ (+0.0311)
recall: base=0.7995 meta=0.8415 ↑ (+0.0420)
roc_auc: base=0.9055 meta=0.9166 ↑ (+0.0110)

In [45]:
X_train_scaled.iloc[:,-4:].corr()

                  OOF_XGBoost  OOF_RandomForest   OOF_MLP   OOF_KNN
OOF_XGBoost          1.000000          0.986725  0.891591  0.827572
OOF_RandomForest     0.986725          1.000000  0.895728  0.834183
OOF_MLP              0.891591          0.895728  1.000000  0.862590
OOF_KNN              0.827572          0.834183  0.862590  1.000000

In [48]:
feature_cols=X_train_scaled.columns
coef_df = pd.DataFrame({
    'feature': feature_cols,
    'coefficient': meta_x_model.coef_[0] 
}).sort_values('coefficient', key=abs, ascending=False)

print(coef_df)

             feature  coefficient
25  OOF_RandomForest     1.631057
24       OOF_XGBoost     1.292643
5                ldl     0.835977
0                age     0.405270
2               chol    -0.403926
15          chol/ldl     0.353689
20         Cluster 3     0.270018
17         Cluster 0     0.254774
6                 cr    -0.237482
22         Cluster 5    -0.162371
10         Age_x_BMI     0.157082
26           OOF_MLP    -0.130542
1                bmi     0.122770
13       BMI/HDL+LDL    -0.118751
12           BMI/LDL     0.117970
19         Cluster 2    -0.105476
3                 tg     0.094706
16    cluster_labels     0.066070
4                hdl    -0.056407
23            gender    -0.040956
21         Cluster 4    -0.038873
14          bun_x_cr    -0.032269
7                bun     0.031440
11         HDL_x_LDL    -0.029786
8      anomaly_score    -0.025182
18         Cluster 1    -0.019848
9             lipids    -0.011004
27           OOF_KNN    -0.006874